### ISSUE TITLE
Support for plugins

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#10]
The mixer should support dynamic discovery/loading of adapters via a plugin model. There are a number of possible approaches, including usage of the coming go 1.8 plugin package.

**Comment by louiscryan** [comment]
@jba I think this is one area where your Go expertise would be most welcome

**Comment by jba** [comment]
Happy coincidence: I just learned about the 1.8 plugin package today. It's definitely the way to go, if you want to go that way.

However, the motivation for the plugin package was the go command-line tool (AFAICT). You're talking about adding plugins to a service, is that correct? I would think that any sort of dynamic code loading for a high-availability service would be destabilizing.

I think you should be really clear about the use cases, and make sure the benefits outweigh the risks.

**Comment by douglas-reid** [comment]
We definitely need more clarity here.

At first blush, the thinking was that it might useful to have a way to load plugins at service (re)start that weren't directly compiled into the mixer. We'd obviously want to find a way to protect the mixer from plugin panics, etc.

**Comment by jba** [comment]
If this a feature to enable third-party users to extend their own mixer instances without touching the code, I can see its benefit.

If it's to enable instances running in Google to be hot-patched without going through a release process, then it's probably unwise. Talk to SRE.

**Comment by louiscryan** [comment]
Definitely the former. This is a pretty common pattern for performance but
extensible platforms in OSS, e.g. nginx

On Fri, Dec 2, 2016 at 8:36 AM, Jonathan Amsterdam <notifications@github.com

**Comment by mandarjog** [comment]
Other reason is to only load adapters that are needed out of all those are available.

Regards, 
Sent from my Ericsson Blaze

Mandar U Jog

**Comment by geeknoid** [comment]
The one big problem with the Go plugin model is likely to be resource consumption. Every plugin will end up being huge and share no code with the mixer proper. Having a dozen adapters loaded as plugins compared to being linked directly into the mixer is likely to be >1G additional RAM consumption, and inherently lower efficiency due to increase CPU cache and TLB miss rates.

I was at first hoping that all adapters would be handled as plugins. But now that I realize the cost, I'm not sure this is a good idea at all. We'll have to measure to know for sure I suppose.

**Comment by 20zinnm** [comment]
Have y'all considered the approach taken by Caddyserver for plugin management? @mholt, the author, knows more about this than I, but basically plugins register themselves in their init function, as shown on the wiki page (https://github.com/mholt/caddy/wiki/Extending-Caddy):

```
import "github.com/mholt/caddy"

func init() {
	// register a "generic" plugin, like a directive or middleware
	caddy.RegisterPlugin("name", myPlugin)

	// register a plugin that can load the Caddyfile when Caddy starts
	caddy.RegisterCaddyfileLoader("name", myLoader)

	// register a plugin that implements an entire server type
	// for use with Caddy
	caddy.RegisterServerType("name", myServerType)

	// register a function that runs when Caddy emits events
	caddy.RegisterEventHook("eventName", myHookFn)

	// add a function that wraps listeners for the HTTP server
	// (it's more common for a directive to call this rather than a standalone plugin)
	httpserver.AddListenerMiddleware(myListenerMiddleware)

	// ... there are others. See the godoc.
}
```

Then, the Caddy buildworker (https://github.com/caddyserver/buildworker) builds Caddy like so:

```
// CaddyPlugin holds information about a Caddy plugin to build.
type CaddyPlugin struct {
	Package string `json:"package"` // fully qualified package import path
	Version string `json:"version"` // commit, tag, or branch to checkout
	Repo    string `json:"repo"`    // git clone URL -- TODO: used?
	Name    string `json:"-"`       // name of plugin: not used here, but used by devportal
	ID      string `json:"-"`       // ID of plugin: not used here, but used by devportal
}

// BuildConfig holds information to conduct a build of some
// version of Caddy and a number of plugins.
type BuildConfig struct {
	CaddyVersion string        `json:"caddy_version"`
	Plugins      []CaddyPlugin `json:"plugins"`
}
```

Finally, as you can see at https://github.com/caddyserver/buildworker/blob/master/buildenv.go#L730, it plugs in all the plugins configured for this build environment before building caddy itself.

I don't know what the memory consumption of Go's plugin system is, but this seems to work well for Caddy.

**Comment by elevran** [comment]
Having plugin's (and especially "binary" plugins) would help the operator in configuring an instance of mixer that's best suited for their environment - either by removing unused components or adding different ones that are environment or tool specific.

This is more of a "packaging" concern, where mixer and plugin's can be compiled independently and assembled when needed for deployment. This can take the form of a Dockerfile (e.g., `FROM mixer-base COPY plugins ...`) or by mounting a plugin's from a shared volume.
In either case, the loading of plugin's happens only at mixer start-up time and is not required to change at run-time. Changes to a deployment should be based on immutable infrastructure - if an update is needed a new deployment artifact should be created.

**Comment by elevran** [comment]
Having looked at Go 1.8 plugin system in more detail for the past few days, I'm concerned that they are too constrained to deliver actual value beyond what's already planned in the 0.2 Mixer design (i.e. separate repo's, pulled in at compile time).
The main limitations I see:

- Support on Linux only (OSX and Windows support may be added in 1.9 or shortly after). I expect most deployments to be Linux based and thus do not think that adding plugin's as an **optional** feature for Linux would be that bad, given what it could provide in terms of operator ease-of-use.
- Plugin's are statically compiled, resulting in a minimal size of 2MB ("hello world" + Go runtime). Again, not sure this is a major limitations, but would depend on the number of loaded plugin's.
- Plugin's require `CGO_ENABLED=1` which may or may not be an issue.
- Plugin's and mixer must use the same Go toolchain (1.8 and 1.8.1 would not work, AFAICT)
- Mixer and all plugin's must use the **same** exact version of all packages/libraries (transitive) or a plugin would fail to load.

The argument for independent compilation and easy assembly is pretty much unattainable in Go 1.8, given the last two restrictions (same toolchain, same dependencies' versions). 

Reading Caddy's source and plugin guide [1] and [2], it would seem that they also require compilation and do **not** use Go 1.8 Plugin's system (caddy.Plugin is not a Go Plugin...).
Caddy did implement some tooling around customizing the build with a set of plugin's (which also seems to be relevant to Mixer and planned in 0.2)

[1] https://github.com/mholt/caddy/wiki/Extending-Caddy#2-plug-in-your-plugin
[2] https://github.com/mholt/caddy/wiki/Writing-a-Plugin:-Directives#4-plug-in-your-plugin

**Comment by elevran** [comment]
Given the above limitations,  it looks like the binary plugin approach won't be really good to pursue for a while yet.
The gRPC based plugin's proposal could help mitigate the concerns around compilation, at the cost of potentially lower performance but with improved reliability.

**Comment by geeknoid** [comment]
This is not on the roadmap for now. If Go gains better dynamic code loading abilities, we can reconsider at that time.
