### ISSUE TITLE
Implement config resolution and dispatch to executors for the new adapter model.

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#1003]
adapterManager/manager.go needs to resolve the new configuration model and dispatch (invoking execute on the executors) the resolved configuration to the new executors (To be implemented https://github.com/istio/mixer/issues/1001)

**Comment by geeknoid** [comment]
Can we close this?

**Comment by guptasu** [comment]
@mandarjog this is done. closing it on your behalf
