### ISSUE TITLE
Fix template codegen issues.

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#1018]
Template names need to be uppercase in the proto, otherwise it produces code that isn't usable. We should flag lower case template names in the proto as an error.

**Comment by guptasu** [comment]
- The generated ConfigureListChecker method doesn't use a name for its argument, but CheckListChecker does. We probably should have names for all arguments in generated code.

**Comment by guptasu** [comment]
@geeknoid using this as an umbrella bug for issues you are reporting.

**Comment by geeknoid** [comment]
Sunny and I chatted and came up with some symbol renames we probably should do:

- Templates should be named after the data they carry (ListEntry, Metric, LogEntry)

- XXXProcessor & XXXProcessorBuilder become XXXHandler & XXXHandlerBuilder

- CheckXXX becomes HandleXXX

- ConfigureXXX becomes ConfigureXXXHandler

**Comment by guptasu** [comment]
File name should not default to _processor

**Comment by geeknoid** [comment]
If a template has no fields, then the generated code contains an unreferenced variable in ProcessCheck or ProcessReport. The md variable is unused:

				var instances []*istio_mixer_adapter_sample_check.Instance
				for name, md := range castedInsts {

**Comment by geeknoid** [comment]
In the generated code, we should try to preallocate slices and maps in order to avoid extraneous allocations at runtime when possible. For example, in ProcessCheck or ProcessReport:

				var instances []*istio_mixer_adapter_sample_check.Instance
				castedInsts := make(map[string]*istio_mixer_adapter_sample_check.InstanceParam)

Both of these could be preallocated to the right size up front.

**Comment by geeknoid** [comment]
Can this be closed?

**Comment by guptasu** [comment]
Yes. I was thinking this bug also refers to fixing the gogo annotation stuff for datatime and duration. But there is a separate bug for that https://github.com/istio/mixer/issues/1029

Closing this
