### ISSUE TITLE
Move template annotations inside Template message.

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#1040]
Currently template variety and template name are on the file level. we want to move them to the message level.

@douglas-reid @geeknoid FYI

**Comment by geeknoid** [comment]
Related:

- Instead of a template name annotation, would it be possible to use the message's own name instead? So instead of calling the message Template and having an annotation stating the template's name is Metric, can we just call the message itself Metric?

- If the annotations are per-message, would it make it possible to define multiple templates in a single package?

**Comment by douglas-reid** [comment]
@geeknoid: defining multiple templates in a single package was one of the reasons why we were asked to move the annotation.

that might also be a way to simplify the naming:  `template.Metric`, `template.Lists`, etc., all within the template package.

**Comment by guptasu** [comment]
Interesting, if we want to define multiple template in the same file, then code we generate needs to include Template name inside it..
Some of the generated code currently does not.
```
type Instance struct
```

```proto
message Type {
```

```proto
message InstanceParam {
```

**Comment by geeknoid** [comment]
​So right now, we have:

metric.Type
metric.InstanceParam

as opposed to having something like:

template.MetricType
template.MetricInstanceParam

I guess I prefer the first case, so I'm cancelling my request to rename
Template to XXX.
​

**Comment by guptasu** [comment]
Just to clarify, Replacing Template to XXX doe not require us to change metric.Instance, metric.Type and metric.InstanceParam -> myPkgName.MetricInstance, myPkgName.MetricType and myPkgName.MetricInstanceParam

Only if we want to support defining multiple templates within the same file (or even make it within the same dir/package with separate files), we will have to do the above prepending of XXXX to synthesized type like instance, Type InstanceParam. 

So, replacing just 'Template' with XXX can be considered as minor improvement on the current syntax. But if we want to support supporting multiple templates in the same package, we will need Template->XXXX anyways.

The real question is do we want to support 'multiple templates in the same package'. I think it will improve readability of the adapter and operator config. explanation below

**# Option 1**
**If we go this route (supporting multiple templates in the same package)**, term like 'Log' will only be used once in any of the fully qualified names because the package name will not contain the term 'Log' in it. Package name will probably end with product name like 'gcp.template'. Full name will become better. (example const string TemplateName will be "mypackageName.LogEntry", Handler interface becomes mypackgeName.LogEntryHandler, Instance type becomes mypackageName.LogEntryInstance),

**# Option 2**
**If we don't go this route (stick with single template per directory/package)**: fully qualified names of certain types will have the term 'Log' (which will be the last node of the package name) spelled out twice. Example: (example const string TemplateName will be "mypackageName.log.LogEntry", Handler interface methods becomes mypackgeName.log.HandleLogEntry),

I think option #1 is good. WDYT ?

**Comment by geeknoid** [comment]
@dougreid is our naming maven... Doug?

**Comment by guptasu** [comment]
@douglas-reid, @douglas-reid , @ZackButcher @mandarjog  : in this bug there are two things proposed:
1. in a template file, move proto option within the message instead of file level.
2. Renaming the fix message name 'Template' -> allowing Any message user wants. This enables multi template scenario. But requires modifying some of the artifacts we create (details of what names will change is in my comment [above](https://github.com/istio/mixer/issues/1040#issuecomment-321397493)).

My question is: Should we go for addressing both 1 and 2 for 0.2 ? I vote yes.

**Comment by geeknoid** [comment]
Can we do 1 and only partially do 2? Specifically, move the proto options
to be message-based rather than file-based, and use the message name as the
template's name, rather than needing a distinct option for this.

We can keep for later the ability to house multiple templates in one
package.

**Comment by guptasu** [comment]
No change needed we will stick with the current model as discussed offline.
