### ISSUE TITLE
Check adapters should be capable of returning data in addition to status

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#1050]
Check adapters that do credential validation will need to send data back to the proxy in addition to status.

1. Change CheckYYY() method signature to return an attributeBag
2. Update codegen to generate calls the new signature.

**Comment by geeknoid** [comment]
I think while discussing this previously I confused myself on this topic. I don't think we want Check adapters to do this, only APAs.

APAs can generate attributes which Mixer should return upon completion of a request. What we're missing now is a mechanism to let Mixer know which attributes should in fact be returned.

**Comment by geeknoid** [comment]
We don't want this feature, until proven otherwise. Feel free to reopen when we have a compelling scenario in hand.
