### ISSUE TITLE
Rename BuilderInfo

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#1054]
I think we should rename adapter.BuilderInfo to adapter.Info and rename GetBuilderInfo to GetAdapterInfo.

The struct is really about describing what an adapter is for, which is the package as a whole. A builder is just a type we use within an adapter.

**Comment by guptasu** [comment]
I remember having it as Info first but unfortunately applicationLog already have has an Info field https://github.com/istio/mixer/blob/master/pkg/adapter/applicationLogs.go#L73

**Comment by geeknoid** [comment]
Hmmm. That's a temporary problem. We'll soon delete that type and then the
name will be available.

**Comment by guptasu** [comment]
Done
