### ISSUE TITLE
Simplify generated symbol names

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#1057]
Right now, for the checknothing template, we are generating the interfaces:

checknothing.CheckNothingHandlerBuilder
checknothing.CheckNothingHandler

I think we can drop the CheckNothing prefix on those interface names. We need to keep the prefix on the methods within these interfaces to overcome Go's limitations, but the Go limitations don't impact those interface names since we quality these by namespace upon use.

**Comment by guptasu** [comment]
Unfortunately, if we want to support multiple templates in the same package, we will  need to keep the prefix on the interface, on the methods as well as on the types we create.
@douglas-reid

**Comment by guptasu** [comment]
Done
