### ISSUE TITLE
Quota handler method doesn't need a QuotaResult

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#1060]
Given the fact a quota handler method already returns a CachaebilityInfo, it doesn't need to also return a QuotaResult, since both structs contain the same info. So let's nuke the QuotaResult value.

**Comment by guptasu** [comment]
is the Amount (total number of quota returned) same as 
// ValidUseCount represent the number of uses for which this result can be considered valid.
ValidUseCount int64

Though the description we have seems slightly different, but it seems they both are for representing how much pre assigned quota is granted. 

Am I right ? Then, I agree, we can nuke the QuotaResult

**Comment by geeknoid** [comment]
Yep, exactly.

**Comment by guptasu** [comment]
So, if we remove the QuotaResult, it feels weird where the response of the QuotaCheck is..
the signature will now look:
```
HandleQuota(*Instance, adapter.QuotaRequestArgs) (adapter.CacheabilityInfo, error)
```

And the information if the quota check passed or failed will be inside CacheabilityInfo..  Seems awkward.

**Comment by guptasu** [comment]
I think the signature is mostly final now. Changes described in the issues are done IMO.
