### ISSUE TITLE
Add benchmark to track perf of attribute package

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#110]
The work done by the attribute package is overhead imposed on every incoming request to the mixer. This code would benefit from tracking and improving perf over time.

**Comment by geeknoid** [comment]
Done.

**Comment by mandarjog** [comment]
benchmark:  https://github.com/istio/mixer/blob/master/pkg/attribute/tracker_test.go#L27

@geeknoid we do need to put in some work to track this and other benchmarks.

**Comment by geeknoid** [comment]
Added issue #115 for the general issue of tracking & reporting perf.
