### ISSUE TITLE
Should we require adapters to implement HandlerBuilder's ConfigureXXX methods

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#1119]
Question is:
1. Should we pass the inferred types information during request time ?
2. If we keep the current model of having ConfigureXXX mtd on HandlerBuidler, should we require every adapter to implement it ?

**Discussion around :1**
@Zack 
_just cache the state once, it lives for the life of the handler
the basic thought is that we hand the shapes in to the runtime methods, so they're usable if they're needed
since every single adapter that needs that info caches it themselves to access it at runtime anyway
why not just provide it at runtime instead, it feels cleaner
the original impetus behind the configure method was when we thought the adapter would have to interact with the backend more to do setup
but we've largely abandoned that thinking with the stance that we don't program backends
we can leave configure around for now and talk more when you get back - but I was convinced we don't strictly need it
oh, actually that was the plan of record anyway, right? that that change was low priority and we'll push it off_

@geeknoid 
_The Configure method is indeed not critical, it's merely highly desirable. We need to support the case where adapters do need to interact with a server in order to prepare the server to receive traffic. It's not acceptable to do this kind of negotiations on first use, we must do all that we can on the configure path and keep the runtime path as simple as we can.
I think it's totally reasonable not to require the Configure methods when they're not needed.
On the flip side, I don't see a substantial gain in competelly eliminating ConfigureXXX methods. It doesn't lead to a simpler model (still are XXX.Type objects), it now forces the use of racy singleton constructs, it precludes expensive server-side setup steps._

**Discussion around :2**
Comments from PR: https://github.com/istio/mixer/pull/1103

_@mandarjog 
_I think it would be much better to not implement the logEntry.HandlerBuilder interface at all, rather than an empty implementation.
       @mandarjog
mandarjog 3 days ago Member
A builder should implement this interface only if it does something meaningful.
       @geeknoid
geeknoid 2 days ago Owner
I thought it was required to be implemented. Making this optional would be great.

@guptasu You on board with that idea? If you declare you support a template in the BuilderInfo struct, it just means you implement the handler, and optionally the handler builder ConfigureXXX method.
       @guptasu
guptasu 2 days ago Member
Hmm.. I think that is too risky since it is prone to spelling mistake errors. Operator might miss spell the method and we will silently stop serving them type information. Too risky I think.
IMO, being strict is better here, writing an empty method is no big deal + adapter developer and his code reviewers will exactly know the reason for the method to be empty.

As I am writing the developer guide, I realize we are doing enough black magic and adding more of a black boxed concept will only add to confusion.

Having said that, if we really want this optional implementation of HandlerBuilder and still have a strict validation, we should ask the adapter developer to explicitly state in BuilderInfo (aka adapter.Info) that he wants just 'Handler' interface part of a particular mesh function. So, declaring just the mesh function name in the BuilderInfo will not be sufficient, they will have to give something in the lines of:
"metric.TemplateName,Handler" or "metric.TemplateName,Handler, HandlerBuilder". Which I think is also a complex concept to understand.
       @mandarjog
mandarjog 2 days ago Member
I think the mis spelling is a valid concern.
However we do not want to force developers to express their intent twice.

A possible solution is, as part of adapter validation tests, we can inspect the handler / builder objects for all public ConfigureXXX methods, and make sure that those are from the allowable universe of methods. Either warn, or error out on a violation.
       @guptasu
guptasu 22 hours ago Member
@mandarjog I think relying on validation tests can be risky, adapter developers might not be following the best practices of running the test suite. Also, I am not sure if we will be able to catch mis spelled method names via pure reflection without causing false positives_._

**Comment by geeknoid** [comment]
As the comment thread shows, I'm opposed to the notion of passing config-time info into the runtime methods.

I am in favor however of not requiring adapters to implement the ConfigureXXX methods if they are not needed. I don't think we need any special protection to prevent misspellings. If the adapter developer writes this call and needs it to get the adapter working, they will figure out their spelling error and fix it, otherwise their adapter won't work.

I suggest we make implementing ConfigureXXX optional and add a log statement to Mixer to report the fact an adapter was found with no ConfigureXXX method:

    adapter 'denier' doesn't implement the ConfigureMetricHandler function, skipping

or something along those lines.

**Comment by guptasu** [comment]
@geeknoid @mandarjog  I am not sure if operator will be happy seeing this warning in his Mixer build every time he builds -> runs a mixer. Adapter developer did the right thing of not implementing what he does not need, but the operator has to feel the pain.

Anyways, whichever rout we go, do you guys think, we can live with the need to define the ConfigureXXXX mtd. We can relax this need post 0.2. Mainly because of lack of time.

**Comment by geeknoid** [comment]
The log message can be limited to V(2) level.

**Comment by geeknoid** [comment]
Let's leave this as-is for 0.2.

**Comment by geeknoid** [comment]
Addressed by updated code gen model.
