### ISSUE TITLE
Renames in Mixer before 0.2

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#1126]
Let's use this issue for tracking what things we need to rename immediately after we delete old model code:
1. BuilderInfo - > Info
2. noop2 -> noop
3. QuotaRequestArgs - > QuotaArgs
4. QuotaResult2 - > QuotaResult
5. inventory2 -  > inventory

what else ? @geeknoid @mandarjog @ZackButcher @douglas-reid

**Comment by geeknoid** [comment]
I think we'll also have:

memquota2 -> memquota
redisquota2 -> redisquota

**Comment by ZackButcher** [comment]
All of the metrics adapters too: prometheus2, statsd2, stackdriver2.

**Comment by guptasu** [comment]
in the config.proto we have action_rules.. that needs to be renamed to rules as well.

**Comment by kyessenov** [comment]
The big one: target -> destination.

**Comment by geeknoid** [comment]
We need to deal with the API repo too. We need to delete the old descriptor protos and find a better location for the ValueType enum.

**Comment by geeknoid** [comment]
Regarding action_rules in the config proto, that should be just action I believe. No rules.

**Comment by sakshigoel12** [comment]
Done
