### ISSUE TITLE
Design and add mixer error interfaces

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#114]
>>> we currently have an uncomfortable tension between programmer vs. operator errors.
>>> 
Options.
1. We use a custom error type that carries an explicitly operator-friendly error string in addition to the developer string
2. Extend error interface with `InteralError ()` If an error implements this interface, it is free to output any message.
All other error must produce operator friendly error messages.

example: https://golang.org/pkg/net/#Error

**Comment by geeknoid** [comment]
I'd like adapters to use a specific error type to report errors such that we have a consistent output to the log. For example, the adapter name should be baked into every error message.
