### ISSUE TITLE
Ensure DNS 1035 compatibility for template names

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#1143]
templateInfo.Name = Template's name must be DNS 1035 label compatible
templateInfo.implementation (field to be added) must be DNS 1035 compatible.

@mandarjog FYI

**Comment by geeknoid** [comment]
Sunny, what's the state of this?

**Comment by guptasu** [comment]
@geeknoid this is done PR https://github.com/istio/mixer/pull/1242
