### ISSUE TITLE
bin/linters.sh is painfully slow

### ISSUE THREAD

**Issue by jmuk** [istio/mixer#1155]
I've been feeling that linters.sh is _very_ slow. On my HP z620 workstation, a run of this script for checking all files takes >7 minutes.

Digging into some of the details, I noticed that `gometalinter.v1` seems the root cause; if we run the head of gometalinter, the performance is improved significantly, it finishes less than a minute (~24 seconds here). I have no idea why / when it's so improved though.

I think the main point of pinning gometalinter through gopkg.in is for pinning linter version (so that it won't report additional errors on existing code), but I believe we should do something better.

**Comment by douglas-reid** [comment]
We pinned to `v1` to attempt to prevent differences in linter results across environments. Any other approach to ensuring consistent linting is also welcome.

I'm skeptical that there was a 14x speed-up across versions. Are you sure it ran the same set of linters on the same set of code?

Gometalinter documentation includes the warning:
> Note that this can be very slow, and you may need to increase the linter --deadline to allow linters to complete.

And I've had to increase the deadline as our codebase has grown for changes that cause the entire repo to be linted.

**Comment by jmuk** [comment]
Checked this a bit more.

The HEAD of `gometalinter` is indeed very fast, with the exactly same set of linters as `v1` has. I skipped `prep_linters` from linters.sh, but still have this result.

Looked into the actual commandlines, I've noticed that the HEAD invokes linters with actual target go files, while `v1` invokes with `.`, I think this is the cause of this huge change.

**Comment by jmuk** [comment]
#1363 fixes this -- at least on my environment. Closing.
