### ISSUE TITLE
Change adapter method signature

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#1159]
- Ditch the `configureXXXX(..) error` method to `configureXXXX(..)`
- Ditch the `ValidateFn(..) error` and have the function on Builder type `func (*builder) Validate(cfg adapter.Config) error`

**Comment by ZackButcher** [comment]
No, I think what we agreed to is:
- `SetFooTypes(map[string]foo.Type)` for each template the adapter implements
- Ditch `ConfigureFooHandler` (configure per template) in favor of `ConfigureAdapter(adapter.Config) adapter.ConfigError` (one configure for the entire Builder)
- `Build(context.Context, adapter.Environment) error`

We will call all of the `Set*` methods, then call `ConfigureAdapter`, then call `Build`

**Comment by guptasu** [comment]
Oho.. yeah... that should have been SetXXXXTypes(..). Copy pasted but didn't edit.
You are right about the BUILD mtd.
@ZackButcher @geeknoid  Regarding ConfigureAdapter(adapter.Config), shall we call it SetAndValidate() ?

**Comment by ZackButcher** [comment]
No, it's not a setter like the others.

**Comment by geeknoid** [comment]
Looking at it written down, I think I prefer adding a whole separate Validate method. So instead of:

SetXXXTypes(...)
SetXXXTypes(...)
SetAndValidate(adapter.Config) error
Build(context, env) (adapter.Handler, error)

You'd have the more symmetrical (but slightly more verbose):

SetXXXTypes(...)
SetXXXTypes(...)
SetAdapterConfig(adapter.Config)
Validate() error
Build(context, env) (adapter.Handler, error)

**Comment by ZackButcher** [comment]
SGTM

**Comment by guptasu** [comment]
@geeknoid and I just chatted about this and may be we can have a single validate method and single Build method that takes all the Types. We can codegen, all the Types for all supported templates in one proto, also throw in the adapter.Config in there. We can then pass this big object to the single Validate method and single Build method. Also get rid of builder completely.

So, Adapter gives two function 
```
func Validate(HandlerConfig) adapter.ConfigErrors
func Build(context.context, Env, HandlerConfig) adapter.Handler, error

type HandlerConfig struct {
  adapterConfig adapter.Config
  quotaTypes []quota.Type
  listEntryTypes []list.Type
  ...
}

type AdapterInfo struct {
  Name string,
  supportedTemplates ...
  validate ValidateFn
  build BuildFn
}
```

**Comment by geeknoid** [comment]
This gets my vote. The semantics are very clear and it eliminates lines of
boilterplate from each adapter.

**Comment by ZackButcher** [comment]
Yeah, I like this best.

**Comment by guptasu** [comment]
Finally we settled on 

SetXXXTypes(...)
SetXXXTypes(...)
SetAdapterConfig(adapter.Config)
Validate() *adapter.ConfigErrors
Build(context, env) (adapter.Handler, error)

Fixed

**Comment by guptasu** [comment]
PR is in, issue is resolved
