### ISSUE TITLE
Replace types.go pattern 

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#117]
I'd like to see the following changes in our current code base:

- Get rid of the types.go pattern. Cramming a bunch of stuff in this kind of 'trash bin' is an anti-pattern as it obfuscate the source base.

- Move adapter-related functionality to pkg/adapter. For example, the adapter registry and the primary Adapter type should be there instead of in aspectsupport.

**Comment by mandarjog** [comment]
done via pr #118
