### ISSUE TITLE
ReferencedAttributes from Mixer is wrong

### ISSUE THREAD

**Issue by qiwzhang** [istio/mixer#1183]
Pilot integration test for this PR(https://github.com/istio/pilot/pull/1152) fail. This PR has mixer client change of using ReferencedAttributes from Mixer to cache Check.

But data returned from Mixer basically disabled check cache.  Here is the log

[libprotobuf ERROR external/mixerclient_git/src/check_cache.cc:145] Referenced attributes: Absence-keys: origin.uid, request.headers, Exact-keys: target.ip, request.host, quota.amount, request.scheme, source.user, request.useragent, source.port, target.service, request.time, request.path, source.ip, request.method, quota.name, source.uid, target.uid, 
W0831 21:58:54.215] [libprotobuf ERROR external/mixerclient_git/src/check_cache.cc:143] Response referenced mismatchs with request
W0831 21:58:54.215] [libprotobuf ERROR external/mixerclient_git/src/check_cache.cc:144] Request attributes: context.protocol: (STRING): http
W0831 21:58:54.215] quota.amount: (INT64): 1
W0831 21:58:54.215] quota.name: (STRING): RequestCount
W0831 21:58:54.215] request.headers: (STRING MAP):
W0831 21:58:54.215]       :authority: a.istio-test-4rhds:8080
W0831 21:58:54.215]       :method: GET
W0831 21:58:54.215]       :path: /b
W0831 21:58:54.215]       accept-encoding: gzip
W0831 21:58:54.216]       content-length: 0
W0831 21:58:54.216]       user-agent: Go-http-client/1.1
W0831 21:58:54.216]       x-b3-sampled: 1
W0831 21:58:54.216]       x-b3-spanid: 00008d70c64f92b0
W0831 21:58:54.216]       x-b3-traceid: 00008d70c64f92b0
W0831 21:58:54.216]       x-forwarded-proto: http
W0831 21:58:54.216]       x-ot-span-context: 00008d70c64f92b0;00008d70c64f92b0;0000000000000000;sr
W0831 21:58:54.216]       x-request-id: f23f153d-6b52-9a17-8e4e-dab4c05c0e4d
W0831 21:58:54.216] request.host: (STRING): a.istio-test-4rhds:8080
W0831 21:58:54.216] request.method: (STRING): GET
W0831 21:58:54.216] request.path: (STRING): /b
W0831 21:58:54.216] request.scheme: (STRING): http
W0831 21:58:54.216] request.time: (TIME ms): 1504216653871968
W0831 21:58:54.217] request.useragent: (STRING): Go-http-client/1.1
W0831 21:58:54.217] source.ip: (BYTES): \x0a\x14\x0eZ
W0831 21:58:54.217] source.port: (INT64): 54594
W0831 21:58:54.217] source.uid: (STRING): kubernetes://b-1655498474-r5f7l.istio-test-4rhds
W0831 21:58:54.217] source.user: (STRING): spiffe://cluster.local/ns/istio-test-4rhds/sa/default
W0831 21:58:54.217] target.ip: (STRING): 10.20.12.163
W0831 21:58:54.217] target.service: (STRING): a.istio-test-4rhds.svc.cluster.local
W0831 21:58:54.217] target.uid: (STRING): kubernetes://a-1518326789-c7mww.istio-test-4rhds

Mixer basically said,  request.headers should be absence.  This is wrong.  It also said that "request.time" should be used for cache.  this is wrong.

**Comment by qiwzhang** [comment]
@mandarjog

**Comment by geeknoid** [comment]
We must have a mismatch in encoding of string indices. It's the first case where Mixer is generating string indices for attributes and the first time the mixerclient is decoding string indices.

I'll check over my code to make sure I can round-trip properly (I encode and decode strings consistently). I suggest you test the same on your end.

**Comment by qiwzhang** [comment]
I think the indexing is fine.  Istio/proxy is using mock mixer (in mixer repo under /test folder) for the integration test and it is using the same global dictionary as real mixer.   My integration test shows that our global dictionary matched.

**Comment by qiwzhang** [comment]
As a reference.  I tested mixer with this simple config

./bazel-bin/cmd/server/mixs server   --configStoreURL=fs://$(pwd)/testdata/configroot

It replied with correct ReferencedAttributes as: only target.service is used as EXACT for both Check and Quota.

**Comment by douglas-reid** [comment]
So, it sounds like the version of mixer used in the pilot integration tests is doing something wonky that we don't see from HEAD. More investigation is need.

**Comment by sakshigoel12** [comment]
@qiwzhang Do you see this issue anymore

**Comment by qiwzhang** [comment]
Check latest Pilot e2e test log(https://storage.googleapis.com/istio-prow/pull/istio_pilot/1249/pilot-e2e-smoketest/363/build-log.txt).  It seems it is working

W0912 14:47:19.550] [libprotobuf INFO external/mixerclient_git/src/check_cache.cc:153] Add a new Referenced for check cache: Absence-keys: destination.service, Exact-keys: request.scheme, quota.name, quota.amount, target.service, target.uid, source.ip, source.port, context.protocol, target.ip, request.headers, request.host, source.user, request.method, source.uid, request.path, request.useragent, request.time,

**Comment by qiwzhang** [comment]
Sorry,  I have to re-open it again.   request.time is in the EXACT keys list.   So it is wrong.

**Comment by sakshigoel12** [comment]
qiwzhang@ can you give an update here?

**Comment by qiwzhang** [comment]
It is fixed

The new log are

W0921 03:21:05.355] [libprotobuf INFO external/mixerclient_git/src/check_cache.cc:153] Add a new Referenced for check cache: Absence-keys: Exact-keys: source.ip, destination.uid, context.protocol, destination.ip, destination.service, source.uid,
