### ISSUE TITLE
Define and Implement Adapter Cache

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#119]
We now have a 2 level adapter cache.

1. Adapter Wrapper Cache
2. AdapterImpl cache

```go

type (
	CacheableMessage struct {
		inner proto.Message
		sha string
	}
)
func NewCacheableMessage (cfg proto.Message) *CacheableMessage{
	cm = &CacheableMessage{
		inner: cfg,
		sha: cfg.String(),
	}
}
```
When a new config is ingested proto messages should be kept with its sha.

For impl configs, sha should be computed after calling DefaultConfig followed by parsing in the `ptype.Struct`

**Comment by mandarjog** [comment]
Check if proto.CompactString imposes ordering on keys of a map.

**Comment by geeknoid** [comment]
Is this addressed by the new adapter manager logic?

**Comment by geeknoid** [comment]
Is this still relevant, can we close?

**Comment by mandarjog** [comment]
This is addressed by handler table.
