### ISSUE TITLE
Mixer IL must support prefix / suffix wildcard matching.

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#1206]
Cexl, supports expression of kind
`selector: target.service == service1.*`

IL does not seem to support it, if this is not supported it is a regression on 0.1

**Comment by ozevren** [comment]
What is the semantics of this? Is it supposed to work with equals with a rhs of string with *, or can the rhs be calculated (i.e. "foo == createPattern()")?

It feels like this should be a function call (i.e. "matches(str, pattern)")

**Comment by mandarjog** [comment]
Ok make it a function call and add fail if you are comparing a string with a literal that contains `*`. Configs *are* using prefix / suffix matches in their configuration.

Can you also run IL evaluator on the eval tests ?
https://github.com/istio/mixer/blob/master/pkg/expr/eval_test.go#L25

We should find out where things differ.

**Comment by kyessenov** [comment]
why not use `target.name=="service1"`?

**Comment by ozevren** [comment]
PR #1240 should unblock this.
