### ISSUE TITLE
Mixer IL should not treat a StringMap miss as a fatal error

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#1208]
Expression written on request.headers should not return an error if the header is missing.
2 choices.
1. Add a test for exits(request.headers["myspecialheader"])
2. treat missing stringmap value as empty string.
```
I0904 07:50:40.390391       1 evaluator.go:182] expression cache miss for 'request.headers["x-user"] == ""'
I0904 07:50:40.390404       1 expr.go:383] Parsed expression 'request.headers["x-user"] == ""' into '&{%!s(*ast.IndexExpr=&{0xc42034bc80 16 0xc42034bca0 25}) %!s(token.Pos=27) == %!s(*ast.BasicLit=&{30 9 ""})}'
I0904 07:50:40.390435       1 evaluator.go:193] caching expression for 'request.headers["x-user"] == ""''
I0904 07:50:40.390450       1 evaluator.go:99] evaluator.EvalPredicate failed expr:'request.headers["x-user"] == ""', err: member lookup failed: 'x-user'
E0904 07:50:40.390475       1 dispatcher.go:153] member lookup failed: 'x-user'
I0904 07:50:40.390479       1 dispatcher.go:224] Check <nil>
E0904 07:50:40.390494       1 grpcServer.go:150] Check2 returned with error : INTERNAL (member lookup failed: 'x-user')
```

**Comment by ozevren** [comment]
I assume this should apply to all stringmap typed things and not just "request.headers"?

**Comment by ozevren** [comment]
BTW conflating "not exists" with "default value" is generally a bad pattern. Have you guys done some previous design work in this area?

It is possible to have the compiler to recognize ~~<potentially failing op> == ""~~ pattern but I am not sure if it is the right thing to do in the general case.

**Comment by mandarjog** [comment]
As the title suggests, it should apply to all stringmaps. 
We *are* missing an `exists` method to test for presence of a header I would use it in that case.

However one would always have to test for presence while comparing any header, which is tedious. 
so
`request.headers["myheader"] == "myvalue"` 
becomes
`exists(request.headers["myheader"]) && request.headers["myheader"] == "myvalue"`

**Comment by ozevren** [comment]
Got it. Pity Go doesn't have a [null-coalesce operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-conditional-operator).

It looks like CEL also doesn't have anything similar to this and uses nulls explicitly. Oh well.
