### ISSUE TITLE
Codegen should use EvalString if type is string

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#1216]
Currently in the generated code in Mixer, we are using Eval to evaluate strings. It seems like expression evaluator returns a nil interface{} if the string is empty (causing npe). Which is wrong. So the fix is to use EvalString when evaluating a fields that is of type string.

@mandarjog is my understanding right about EvalString method (may be that is why it was introduced to begin with)

after this fix, fix this pr too: https://github.com/istio/istio/pull/679

**Comment by guptasu** [comment]
This problem is across all primitives. Eval on empty string returns nil. Once we fix https://github.com/istio/mixer/issues/1220 (allowing operators to skip specifying the fields completely), we will need to tackle how the Eval should be called during runtime dispatch and handle the nil object correctly when filling in the Instance object.

**Comment by guptasu** [comment]
Since in 0.2 we always require the field to be set inside the instance configuration (for all fields in the template), this problem is easily solved by checking if the expression is not "" or is not '""'. These two checks during configuration time will ensure we never evaluate an `""` strings during request time. PR https://github.com/istio/mixer/pull/1246 enforces empty expressions during configuration time.

In 0.3, if we do not always need an expression for a field in instance config, we will need to decide on some defaults for those fields (example strings "", int = 0, etc.). When we make that change, we will need to address this potential NPE in generated code caused by using eval result of empty expression.

@ZackButcher @mandarjog FYI

**Comment by guptasu** [comment]
Moving this to 0.3

**Comment by geeknoid** [comment]
Is the title of this issue still appropriate?

**Comment by guptasu** [comment]
This is a dupe of https://github.com/istio/mixer/issues/1456. Closing this issue in favor of the latest one.
