### ISSUE TITLE
IL expression evaluator can't handle expression like request.headers["xxx"] = xxx

### ISSUE THREAD

**Issue by manlinl** [istio/mixer#1233]
AST expression  evaluator works file for
https://github.com/istio/mixer/blob/master/testdata/config/deny.yaml

But IL evaluator doesn't work.

**Comment by guptasu** [comment]
@mandarjog @douglas-reid @ZackButcher @geeknoid FYI

**Comment by ZackButcher** [comment]
While we're at it, IL eval should also handle `stringmap.attribute[other.attribute]` where `other.attribute` is a `STRING` attribute, and not just string literals as keys.

**Comment by ozevren** [comment]
There is nillability case that I am fixing right now:
https://github.com/istio/mixer/pull/1221

Haven't looked at the original issue on this thread, but I am assuming it
is related (stringmap lookup works for non-nil case)

{
 expr: `ar["foo"] == "bar"`,
 input: map[string]interface{}{
  "ar": map[string]string{
   "foo": "bar",
  },
 },
 result: true,
},

Also, for non-nil case stringmap.attribute[other.attribute] already works.

{
 expr: `ar[as]`,
 input: map[string]interface{}{
  "ar": map[string]string{
   "c": "b",
  },
  "as": "c",
 },
 result: "b",
},

**Comment by ozevren** [comment]
PR #1221 is  in now. Manlin, could you try your case with the latest bits?

Thanks

**Comment by guptasu** [comment]
@manlinl I think we can now change your test to set useAst to false.
