### ISSUE TITLE
IL expression  "|" func incorrectly returns unresolved attribute error

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#1254]
`context.protocol | "bgp"`  express should not result in an error because the attribute is missing.

This is an excerpt from the log.

```
I0909 15:01:32.800660   11966 evaluator.go:188] evaluator.getOrCreateCacheEntry failed expr:'context.protocol | "bgp"', err: unresolved attribute context.protocol
I0909 15:01:32.800671   11966 evaluator.go:167] evaluator.evalResult failed expr:'context.protocol | "bgp"', err: unresolved attribute context.protocol
I0909 15:01:32.800681   11966 evaluator.go:77] evaluator.Eval failed expr:'context.protocol | "bgp"', err: unresolved attribute context.protocol
```

@douglas-reid you are also familiar with this code.

**Comment by mandarjog** [comment]
I have observed that it works ok after a config change. Perhaps IL is not getting the correct vocabulary at startup ?

**Comment by ozevren** [comment]
Possibly.

https://github.com/istio/mixer/blob/master/cmd/server/cmd/server.go#L355
This is where the finder IL evaluator gets registered as a listener to the
config manager and should be getting the metadata through the event
callback interface.

I am not sure how the timings of this is supposed to work here though. When
I was initially doing this work, I tried spelunking and trying to figure
out exactly where the metadata is set for the AST based implementation, but
I believe it was a bit too deep in the stack. With Config Manager, I
thought this model would be the right way to get the initial config
changes. Do we need to perform the initial config metadata setup explicitly?

**Comment by mandarjog** [comment]
related to #1267

**Comment by mandarjog** [comment]
This was a misleading error message. It should have been "unknown attribute". It has been fixed now.
