### ISSUE TITLE
istio/istio e2e ratelimit test fails reliably if upgrading mixer to latest (seemingly because of unknown)

### ISSUE THREAD

**Issue by ldemailly** [istio/mixer#1286]
when using latest mixer with latest pilot/envoy

qps is >> 1 qps
I0913 07:15:01.592] Ended after 1m0.39100059s : 596 calls. qps=9.869

but everything goes to 200s
```
I0913 07:15:32.079] 		request_count{instance="istio-mixer.mixer-test-630de8e3c3af4d259c38c06de1:42422", job="istio-mesh", method="/productpage", response_code="200", service="unknown", source="unknown", target="ingress.mixer-test-630de8e3c3af4d259c38c06de1.svc.cluster.local", version="unknown"} => 608 @[1505286931.554]
```

and no 429s at all

for instance:

https://k8s-gubernator.appspot.com/build/istio-prow/pull/istio_istio/775/e2e-suite-rbac-auth/531/

(I have https://github.com/istio/istio/pull/776  for better ratelimit output in that case but that's would be cosmetic, the failure is the issue)

**Comment by mandarjog** [comment]
This is because https://github.com/istio/istio/pull/725 is not merged yet.

**Comment by mandarjog** [comment]
There is still some problem, investigating...

**Comment by ldemailly** [comment]
it was the config issue, my bad
(this being said the unknown are maybe suspicious)
