### ISSUE TITLE
Make mixer robust to adapter failures

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#131]
The mixer needs to handle:

- Panics in adapter methods
- Timeouts in adapter methods
- Needs to perform type validation of configs before they reach the adapters.

**Comment by ZackButcher** [comment]
After https://github.com/istio/mixer/pull/165 lands it'll be relatively straight-forward to beef up how we dispatch to our adapters:
1. We push the uber.manager.Execute call off to another thread, poll its result and the ctx's done channel, stopping if we deadline exceed.
2. The func we wrap around the call to uber.manager.Execute will be responsible for recovering from panics.

Handling config (and its validation) is still up in the air.

**Comment by ZackButcher** [comment]
All of the cases originally laid out are handled today. The only open hole we're currently aware of is that an adapter can create another go routine and panic in it, bringing down the mixer. It's unclear what we can do to prevent this programmatically.
