### ISSUE TITLE
Mixer Template Developer's Guide

### ISSUE THREAD

**Issue by sakshigoel12** [istio/mixer#1315]

**Comment by guptasu** [comment]
@ZackButcher can you help out with this documentation. I don't think I will be able to get to this given the edits I have to make to the Adapter dev guide

**Comment by sakshigoel12** [comment]
Sometime next week. Martin to help

**Comment by sakshigoel12** [comment]
@geeknoid I have seen the adapter guide. Does  that include the template guide as well? Can we close this

**Comment by guptasu** [comment]
This is done too.
https://github.com/istio/mixer/blob/master/doc/dev/templates.md
