### ISSUE TITLE
Mixer: Update docs for Configuration

### ISSUE THREAD

**Issue by sakshigoel12** [istio/mixer#1316]

**Comment by sakshigoel12** [comment]
@mandarjog can you add an ETA

**Comment by jasminejaksic** [comment]
Can you please complete this by COB tomorrow?

**Comment by mandarjog** [comment]
Only `listchecker` documentation remains in the end user configuration area.
mtail is working on it.

**Comment by geeknoid** [comment]
Covered by issue #570 in the doc repo.
