### ISSUE TITLE
Update Mixer Architectural Overview Docs

### ISSUE THREAD

**Issue by sakshigoel12** [istio/mixer#1318]

**Comment by douglas-reid** [comment]
I've update the main Mixer concept doc. @mandarjog was going to update the Mixer Config doc.

When that is complete, we will need to decide what/how to update the Mixer Aspect Config doc.

Assigning to @mandarjog for the Mixer Config doc update.

**Comment by mandarjog** [comment]
This https://github.com/istio/istio.github.io/pull/527 is out for review.

**Comment by geeknoid** [comment]
This is all happy.
