### ISSUE TITLE
Question: Where is "HandleMetric" defined?

### ISSUE THREAD

**Issue by rlguarino** [istio/mixer#1328]
All of the Metrics adapters seem to be implementing an interface which requires the function `HandleMetric(_ context.Context, vals []*metric.Instance) error`. For example [prometheus](https://github.com/istio/mixer/blob/master/adapter/prometheus/prometheus.go#L178) and [stackdriver](https://github.com/istio/mixer/blob/master/adapter/prometheus/prometheus.go#L178). 

I expected to see that function defined somewhere in the template [here](https://github.com/istio/mixer/blob/master/template/metric/template.proto), but I'm not seeing it. GitHubs code search isn't helping either. The best result I can find is [ReportTmpl.go.golden](https://github.com/istio/mixer/blob/916236cfbcfe4530d2b3c8012b3e2a0074c3e0ad/tools/codegen/pkg/interfacegen/testdata/ReportTmpl.go.golden) but that says it's generated... but I can't find by what. [this](https://github.com/istio/mixer/blob/916236cfbcfe4530d2b3c8012b3e2a0074c3e0ad/pkg/adapter/template/TemplateExtensions.proto) file seems to have something to do with it.. but I'm having a hard time following the dots.

**Comment by rlguarino** [comment]
OH is it just "Handle<TemplateName>"?

**Comment by mandarjog** [comment]
@rlguarino an adapter developer's guide will be published in next 2 weeks.
You can look [noop adapter](https://github.com/istio/mixer/blob/master/adapter/noop/noop.go)
which consumes all templates.

You can also look at [code gen](https://github.com/istio/mixer/blob/master/tools/codegen/pkg/interfacegen/template/interface.go#L73) for details.
