### ISSUE TITLE
Prometheus adapter not working for Linear buckets and exponential buckets.

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#1331]
prometheus.go references types from pkg/adapter/metrics.go. Ideally that file pkg/adapter/metrics.go should be deleted and //adpater/prometheus should only know about template types or it's own config. In this case it seems like the prometheus should be referencing config.<types> instead of old structs from pkg/adapter/metrics.go

Because of same named types, prometheus is trying to cast types from config.<adapter specific config> into //pkg/adapter/metric.<some types types like Exponential buckets...>. But that does not work because the types inside the adapter/prometheus/config/ dir is is different from the one inside //pkg/adapter/metric.go. NOTE:  This is not caught during compile time because in the prometheus code we convert the objects into `interface{}` and then try to do a type conversion. Because of the hop to interface, golang compiler will not complaint.

code that does the cast and should be fixed:
https://github.com/istio/mixer/blob/master/adapter/prometheus/prometheus.go#L264

This needs to be done for 0.2.

**Comment by guptasu** [comment]
@mandarjog @ZackButcher @douglas-reid FYI

**Comment by douglas-reid** [comment]
OK to close?

**Comment by guptasu** [comment]
yes. fixed
