### ISSUE TITLE
testenv package cause cyclic dep when used from adapter package

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#1343]
trying to add a test in the adapter package that uses the test env cause a cycle deps
```
istio.io/mixer/adapter/mysampleadapter
import cycle not allowed in test
package istio.io/mixer/adapter/mysampleadapter (test)
	imports istio.io/mixer/test/testenv
	imports istio.io/mixer/cmd/server/cmd
	imports istio.io/mixer/adapter
	imports istio.io/mixer/adapter/mysampleadapter
```
FAIL	istio.io/mixer/adapter/mysampleadapter [setup failed]

This is critical in order to allow the adapter developers to write tests in their code base and also use our testenv.

**Comment by manlinl** [comment]
This is pretty natural. testenv depends on a

**Comment by guptasu** [comment]
//adapter is a completely pluggable module and ideally should not be referenced from `istio.io/mixer/cmd/server/cmd`. However, I just looked into it, we are unfortunately referencing //adapter to access the LegacyInventory at two places in /cmd/server/cmd . For example https://github.com/istio/mixer/blob/master/cmd/server/cmd/server.go#L297

I propose we move the [legacy Inventory.go](https://github.com/istio/mixer/blob/master/adapter/inventory.go) outside the //adapter directory. This should achieve braking the cyclic dep when trying to use testenv from adapter test code.

Thoughts Mixers ? @geeknoid @mandarjog @douglas-reid @ZackButcher @manlinl

**Comment by guptasu** [comment]
I think the right solution will be to parameterize the legacy inventory too, like how we have parameterized the new inventory. The main.go passes the value. I will send a PR.

**Comment by douglas-reid** [comment]
@guptasu yeah, i believe this is closely related one of the last bits of dependency handling that we need to address before full builds of mixer from other repos too. thanks for tackling.

**Comment by guptasu** [comment]
Please review https://github.com/istio/mixer/pull/1346.
