### ISSUE TITLE
build broken with bazel 0.6.0

### ISSUE THREAD

**Issue by jmuk** [istio/mixer#1365]
I've gotten build errors as follows:

```
% bazel build //...
ERROR: /usr/local/google/home/mukai/.cache/bazel/_bazel_mukai/23d88ec2f9449b2c9d846b080b7cc444/external/io_bazel_rules_go/go/private/binary.bzl:226:48: name 'lib' is not defined (did you mean 'libs'?)
ERROR: error loading package '': Extension 'go/private/binary.bzl' has errors
ERROR: error loading package '': Extension 'go/private/binary.bzl' has errors
INFO: Elapsed time: 0.132s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Seems this is because of bazel 0.6.0?

I had another environment which still stays on bazel 0.5.4. Succeeded to build, but started reporting the same error after upgraded to 0.6.0.

**Comment by douglas-reid** [comment]
Is `rules_go` ready for 0.6.0 ?

**Comment by jmuk** [comment]
I don't know. Needs more investigation.

**Comment by kyessenov** [comment]
Beware of the change in go to 1.9. We've been holding off in pilot after the release to update rules.

**Comment by yusofg2** [comment]
I am trying to build mixer and hit this issue. Any workarounds or ETA for a fix?

**Comment by kaledj** [comment]
@yusofg2 For a workaround, I downgraded to bazel 0.5.4 (https://github.com/bazelbuild/bazel/releases/tag/0.5.4) per the original comment, and was able to build mixer

**Comment by jmuk** [comment]
Yeah, better to keep using 0.5.4 for the time being. That's what I'm doing too.
#1366 should fix the issue, but we decided to hold it due to our release schedule.
