### ISSUE TITLE
upgrade go to 1.9?

### ISSUE THREAD

**Issue by jmuk** [istio/mixer#1442]
`rules_go` dependency has been done (for bazel 0.6.1 support), which enables us to upgrade go version from 1.8.3 to 1.9.1.

When and how do we do this update?

**Comment by jmuk** [comment]
- I don't see any breaking changes from 1.9 release notes and 1.9.1 updates, the existing mixer code should work as-is
- `bazel test //...` succeeds with go 1.9.1
- benchmark tests are not changed significantly

**Comment by douglas-reid** [comment]
I think we should do this now that we are past the 0.2.x releases.

**Comment by jmuk** [comment]
https://github.com/istio/mixer/pull/1452

**Comment by jmuk** [comment]
resolved
