### ISSUE TITLE
//pkg/il/evaluator:go_default_test timeouts during pre-push

### ISSUE THREAD

**Issue by apicl** [istio/mixer#1503]
Error message:

//pkg/il/evaluator:go_default_test                                      TIMEOUT in 60.1s

**Comment by ozevren** [comment]
Is there a link to the failing test? evaluator tests run at ~9secs on my laptop. 60 sec timeout implies more than 6x time dilation.

**Comment by apicl** [comment]
https://github.com/istio/mixer/issues/1503

If I "bazel test" locally, it works fine. It failed during the pre-push
phase.



Thanks
Chengliang

**Comment by apicl** [comment]
Fixed in https://github.com/istio/mixer/commit/08f4f364d914684ece832c7d9635b81dba0f702f
