### ISSUE TITLE
Question: Does the attribute request.headers include grpc Metadata?

### ISSUE THREAD

**Issue by rlguarino** [istio/mixer#1542]
The docs [here](https://istio.io/docs/reference/config/mixer/attribute-vocabulary.html) for "request.headers" the attributes say "HTTP request headers" I don't think grpc metadata is sent over HTTP headers but I could be wrong.

**Comment by geeknoid** [comment]
Wayne, could you answer the question and update the docs to make the answer clear?

Thanks.

**Comment by geeknoid** [comment]
Ping: Wayne?

**Comment by rlguarino** [comment]
Any update on this?

**Comment by qiwzhang** [comment]
Sorry, I somehow missed it.  Yes,  gRPC metadata will be send over in the "request.headers" attribute.

**Comment by qiwzhang** [comment]
https://github.com/istio/istio.github.io/pull/816
to update the doc
