### ISSUE TITLE
Build docker images in CI

### ISSUE THREAD

**Issue by kyessenov** [istio/mixer#162]
Please build server docker images in your CI/CD workflow to be utilized by Istio manager.
Common pattern is to tag your images as:
    gcr.io/istio-testing/mixer-alpha:GIT_SHA

**Comment by douglas-reid** [comment]
docker images are now being generated on successful merges by travis and pushed to GCR (istio-test GCP project). there is likely more work to do to keep the image building current with config changes, etc., but I'm marking this issue as closed for now.
