### ISSUE TITLE
Switch protobuf-related codegen to gogoprotobuf

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#163]
https://github.com/gogo/protobuf provides more convenient protobuf code gen with (ostensibly) considerably faster marshalling/demarshalling code.

**Comment by douglas-reid** [comment]
More convenient how?

We have a bazel-ified setup now. I don't see anything about gogoprotobuf being bazel-friendly. This would require a rewrite of our existing codegen build setup entirely.

**Comment by kyessenov** [comment]
Codegen does not have to be bazelified if you are willing to commit the generated code in.
Convenience for programming is more important the build setup.

**Comment by mandarjog** [comment]
It does look like the generated code is just better. I will check about some extensibility if it can be used right away.

Otherwise this is a post 1.0 effort

**Comment by geeknoid** [comment]
I definitely referred to convenience for the programmer, given all the code
gen options it offers. Yes, this would require some updates to our build
procedures, although I don't think it would be substantial.

The perf improvements for marshalling and unmarshalling is quite
substantial, definitely worth chasing. I'm surprised in fact that these
improvements haven't been rolled into the main proto code gen modules.
