### ISSUE TITLE
Provide adapter infrastructure

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#170]
Tracking issue:

Mixer should provide a complete end-to-end story for adding adapters to the codebase and using them in a live system.

We have a bunch of this in place already. There is some refactoring and a bit of config-related work that needs to be done.

**Comment by douglas-reid** [comment]
This includes the discussed multiple execution phases, etc. @geeknoid, I think your work on fork-join attribute semantics is part of this, so I'm assigning you for now.

**Comment by douglas-reid** [comment]
Why is this closed?  We still do not have multiple execution phases in the mixer.

**Comment by geeknoid** [comment]
We closed it 'cause I think the general theme here has been addressed. I opened #475 and #476 to track the more specific work items.
