### ISSUE TITLE
Add AttributeMapping adapter (evaluator) to mixer

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#171]
Mixer needs ability to map from input attributes to params requested in aspect configs, etc.

**Comment by geeknoid** [comment]
This doesn't need to be an adapter, right? This is just part of our config expression evaluation stuff?

**Comment by douglas-reid** [comment]
At one point, we were thinking that this piece itself would be pluggable. I think that is why we called it an adapter. I just took the name from one of the docs. I don't think it needs to be an adapter in the sense of the internal interfaces, etc.

**Comment by mandarjog** [comment]
duplicate of #475
