### ISSUE TITLE
Restore bazel caching in travis build

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#195]
At some point, it would be nice if we could restore the caching we used to have for bazel in the travis builds.  It would declutter the build logs, provide more rapid builds, and (potentially) help with docker image building too.

**Comment by mandarjog** [comment]
done.

**Comment by douglas-reid** [comment]
Re-opening to track desire to have the docker image building work off of the same cache.

**Comment by douglas-reid** [comment]
Closing, as docker image build now uses same cache.
