### ISSUE TITLE
Add handling of descriptor protos into mixer

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#197]
Right now, we have placeholders for log_entry_descriptors and the like in our codebase. We need to properly plumb them throughout the codebase, making them available to managers, and perhaps adapters (metrics backend programming, etc.).

**Comment by mandarjog** [comment]
@douglas-reid you think this is needed for NEXT?

**Comment by ZackButcher** [comment]
Now that all aspect validation has been implemented all that's left is to validate Descriptors themselves.

**Comment by douglas-reid** [comment]
@ZackButcher any update in status?

**Comment by ZackButcher** [comment]
Did we decide to punt descriptor validation to post alpha? Otherwise I can implement pretty easily, just haven't been treating it as a priority.

**Comment by geeknoid** [comment]
Can this be closed?

**Comment by ZackButcher** [comment]
Yup, with https://github.com/istio/mixer/pull/613 this is done.
