### ISSUE TITLE
Support for single adapter object providing multiple builders 

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#204]
Add support for single Adapter providing multiple Builders.

This involves.
1. Removing global adapterName uniqness. (adapterName, aspectKind) must be unique.
2. Removing "Kind" property from Adapter proto.
    This enables an adapter to assert multiple "Kinds" in the code.

This enables a GCP Adapter to provide builders for multiple GCP Aspects.

The above changes enable code like the following.

`adapter/stdioLogger/stdioLogger.go`

would like to register - 
```
b := builder{adapter.NewDefaultBuilder(name, desc, conf)}
 r.RegisterLogger(b)
 r.RegisterAccessLogger(b)
```
instead of 
```
	r.RegisterLogger(builder{adapter.NewDefaultBuilder(
 		"istio/stdioLogger",
 		"Writes structured log entries to a standard I/O stream",
 		&config.Params{},
 	)})
 	r.RegisterAccessLogger(builder{adapter.NewDefaultBuilder(
 		"istio/stdioAccessLogger",
 		"Writes structured access log entries to a standard I/O stream",
 		&config.Params{},
 	)})
```

**Comment by mandarjog** [comment]
After this issue is resolved update `adapter/stdioLogger/stdioLogger.go#Register()`

**Comment by geeknoid** [comment]
Done.

**Comment by mandarjog** [comment]
Keeping it open for.
Removing "Kind" property from Adapter proto.

**Comment by geeknoid** [comment]
Addressed by new adapter model.
