### ISSUE TITLE
Define naming scheme for adapters

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#225]
So far, we've been prefixing everything with `istio/`.  It isn't clear exactly how/when that prefix should be used (should we use `istio/prometheus` or `prometheus`?). It also isn't obvious that the prefix is meaningful or useful for operators.

We should define a clear scheme for naming and document that scheme, etc.

This probably will be influenced by work on #204, as right now the same builder gets registered under two names. If #204 is not addressed in the short term, we might consider a naming scheme that looks more like `stdio/logger` and `stdio/accessLogger` than our existing `istio/stdioLogger` and `istio/stdioAccessLogger`, as an example.

**Comment by geeknoid** [comment]
Aspect kinds also factor in here. Aspect kinds also have an istio/ prefix, and they've got an inconsistent style. So overall, this is what I'd like to do:

#1. For aspect kinds, drop the istio/ prefix and rationalize the naming style. Thus, the given aspect kinds would be:

  access-logging
  general-logging
  list-checking
  metric-reporting
  quota-management

(and we fold denyChecker into list-checking, it's definitely not worth a whole aspect of its own)

#2. For adapter names, go with strictly the directory name of the adapter. No additional prefix/suffix

#3. We allow multiple adapters to be registered with the same name, as long as they are for different aspects.

**Comment by douglas-reid** [comment]
RE: 1 - Dropping `istio/` seems reasonable. I think in our earlier conversations there was a preference for shorter, non "-ing" names, so maybe something like: access-logs, application-logs, metrics, quotas, and whitelist/blacklist (aliases for list checking with default enforcement).

RE: 2 - Going with package names is fine by me... but I think we still want consistency there too (prometheus v. ipListChecker, etc.).

RE: 3 - In #204, the idea is to have a _single_ adapter register for different aspects. So, it only has one name, but can be registered twice. So I think we are all on the same page there.

**Comment by geeknoid** [comment]
Done.
