### ISSUE TITLE
Enable fancy gogoprotobuf code gen options

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#238]
We should enable the extra code gen options for gogoprotobuf which would give us faster RPC and more idiomatic generated Go code.

**Comment by douglas-reid** [comment]
Do you have a list of the options that you'd like to see enabled?  I'm not sure what is possible with our current build setup, so I'd like to understand which flags, etc., we want.

**Comment by douglas-reid** [comment]
Related: https://github.com/pubref/rules_protobuf/pull/63

**Comment by geeknoid** [comment]
I'm mostly interested in the speed-related stuff. gogofast and gogofaster I
believe they're called. The improvements in the shape of the generate
protos from a usability perspective would be nice, but not as compelling
IMO.

**Comment by douglas-reid** [comment]
OK. We should now be able to switch easily over to gogofaster. I'll give it a shot soon.

**Comment by douglas-reid** [comment]
I've switched everything to gogoslick (which is gogofaster + string, gostring, and equals methods on protos).

This should give us the fast marshal/unmarshal support.  Other improvements can be added on a case-by-case basis.

Closing general issue.
