### ISSUE TITLE
Service Graph Adapter  #demo

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#249]
Write a mixer (metrics? ) adapter that generates service graphs based on what has been seen so far.

This adapter will serve the graph over an http endpoint.
http://mixer:$port/api/serviceGraph?time_horizon={5min, 1hr, 12hr, 1day}

It should return the following graph.
UI will paint the graph and annotate vertices and edges with specified labels.
`name, status, src, dest` are well known attributes of the objects. These can be interpreted by the UI. `status` can be used to color code the graph. 

```
{
nodes: [
{ "name": "service1", "status": "warning",
   labels: { "k1": "v1", ...}
},
{ "name": "service2", "status": "error",
   labels: { "k1": "v1", ...}
}, 
 
...
],
edges:[
{ src: service1, dest: service2, "status": "ok",
   labels: { "req/s": "200", "err_rate": "2", "latency": "2" } 
},
...

}
```

**Comment by mandarjog** [comment]
After more discussions, here are some more alternatives.

1. Define all the (prometheus/statsd) metrics that are necessary to extract a service graph later.
For example:
latency, labels:{"targetService", "sourceServiceAccount", ... }
2. Write a separate program that uses data from premetheus or statsd to return the graph as defined above.

**Comment by douglas-reid** [comment]
initial thoughts:
- add new pkg and adapters to istio/mixer codebase for graph generation
- build separate binary within mixer for graph generation
- adapters use query languages provided by backends to generate graphs.

**Comment by douglas-reid** [comment]
secondary thoughts:
- isolate everything in //pkg/servicegraph and //cmd/server for now, as we do rapid prototyping
- use an existing golang graph model lib for unified data model (prototyping)

**Comment by douglas-reid** [comment]
Current status:

A basic HTTP endpoint has been committed to the repo, with the following characteristics:

 - `/graph` which provides a JSON serialization of the servicegraph
 - `/dotgraph` which provides a dot serialization of the servicegraph
 
All endpoints take an optional argument of `time_horizon`, which controls the timespan to consider for graph generation. `time_horizon` args should be prometheus duration strings (examples: 5m, 2h, 3d).

For an example scenario, HTTP GET of `/graph?time_horizon=15m` returns the following:

```
{"nodes":{"App 0":{},"App 1":{},"App 2":{}},"edges":[{"source":"App 2","target":"App 1","labels":{"qps":"0.420606","service":"Service 3"}},{"source":"App 0","target":"App 2","labels":{"qps":"0.536762","service":"Service 0"}},{"source":"App 1","target":"App 2","labels":{"qps":"0.444819","service":"Service 0"}},{"source":"App 1","target":"App 2","labels":{"qps":"0.394876","service":"Service 3"}},{"source":"App 1","target":"App 2","labels":{"qps":"0.395316","service":"Service 1"}},{"source":"App 0","target":"App 2","labels":{"qps":"0.466972","service":"Service 4"}},{"source":"App 2","target":"App 0","labels":{"qps":"0.422174","service":"Service 1"}},{"source":"App 2","target":"App 0","labels":{"qps":"0.376054","service":"Service 4"}},{"source":"App 1","target":"App 0","labels":{"qps":"0.531859","service":"Service 3"}},{"source":"App 1","target":"App 0","labels":{"qps":"0.361601","service":"Service 2"}},{"source":"App 1","target":"App 2","labels":{"qps":"0.394243","service":"Service 2"}},{"source":"App 2","target":"App 0","labels":{"qps":"0.392670","service":"Service 2"}},{"source":"App 2","target":"App 0","labels":{"qps":"0.427079","service":"Service 3"}},{"source":"App 0","target":"App 1","labels":{"qps":"0.428597","service":"Service 1"}},{"source":"App 2","target":"App 0","labels":{"qps":"0.470992","service":"Service 0"}},{"source":"App 0","target":"App 1","labels":{"qps":"0.449130","service":"Service 2"}},{"source":"App 0","target":"App 1","labels":{"qps":"0.431486","service":"Service 4"}},{"source":"App 0","target":"App 2","labels":{"qps":"0.345033","service":"Service 3"}},{"source":"App 0","target":"App 2","labels":{"qps":"0.473147","service":"Service 2"}},{"source":"App 0","target":"App 2","labels":{"qps":"0.337191","service":"Service 1"}},{"source":"App 2","target":"App 1","labels":{"qps":"0.491379","service":"Service 1"}},{"source":"App 2","target":"App 1","labels":{"qps":"0.407472","service":"Service 0"}},{"source":"App 1","target":"App 2","labels":{"qps":"0.510882","service":"Service 4"}},{"source":"App 2","target":"App 1","labels":{"qps":"0.464975","service":"Service 2"}},{"source":"App 0","target":"App 1","labels":{"qps":"0.398524","service":"Service 3"}},{"source":"App 1","target":"App 0","labels":{"qps":"0.416198","service":"Service 4"}},{"source":"App 1","target":"App 0","labels":{"qps":"0.389387","service":"Service 1"}},{"source":"App 2","target":"App 1","labels":{"qps":"0.410707","service":"Service 4"}},{"source":"App 1","target":"App 0","labels":{"qps":"0.455502","service":"Service 0"}},{"source":"App 0","target":"App 1","labels":{"qps":"0.479862","service":"Service 0"}}]}
```

**Comment by mandarjog** [comment]
@vin Is this ok for you?

**Comment by vin** [comment]
Yes this looks fine, thanks!

**Comment by douglas-reid** [comment]
there is now a docker build for the servicegraph backend.  @mandarjog should we get the plori guys to include this in their demo setup?

**Comment by douglas-reid** [comment]
Should we close this issue and open another for long-term servicegraph support?

**Comment by douglas-reid** [comment]
Closing. We can track need for better servicegraph in another issue.
