### ISSUE TITLE
Concerns about expression language expressive power

### ISSUE THREAD

**Issue by kyessenov** [istio/mixer#259]
From my brief introduction to the selector expression language, it appears to me where we're on the path to a full ad-hoc Turing-complete programming language. Custom functions and applications, arbitrary operators, variables? are all great and easy to use for programmers but they will cause significant problems with:
- building good analysis tools and UIs for the selector language; general purpose languages are not amenable to many useful analysis techniques
- lower-lever configuration formats; all the features have to propagate down to proxy network level, and at that level there is not much context
- yet another configuration language incurs significant cognitive load

I would like us to try to find a smaller language that's useful yet concise instead of taking-on Go parsing/language infrastructure.

**Comment by mandarjog** [comment]
Can you provide a few examples where the current approach does not work ?

- AST for the language is simple.  symbols / literals and functions.
- Every expression is fully typed.
- We can switch out the front end (parser / lexer) if the language syntax is an issue
- Not every parseable expression is valid; We support very few functions.
- Not sure what is the *other* configuration language?

**Comment by geeknoid** [comment]
We're adopting the CEL grammar.
