### ISSUE TITLE
Decide singular or plural for directory+package names

### ISSUE THREAD

**Issue by wora** [istio/mixer#26]
This is one of classic naming issues. Many traditional names, such as "/usr/bin", "/usr/lib", "java.util", use singular names. While plural name is perfect valid choice when you look at it specifically, but it is often out of place in symbols, such as "com.google.api.services.gmail.Gmail". It looks awkward to have a plural word in the middle of many singular words.

It would be better to always use singular word for all directory names, then we don't need to debate the choice case by case.

**Comment by kyessenov** [comment]
Can you update your development style guide https://github.com/istio/mixer/blob/master/docs/devel/conventions.md to define your naming choices? I think the rest of Istio would want to adopt these conventions.

**Comment by wora** [comment]
This is fixed by https://github.com/istio/mixer/pull/28.
