### ISSUE TITLE
Refine aspect error handling

### ISSUE THREAD

**Issue by ZackButcher** [istio/mixer#260]
Due to the shape of the MetricAspect's Record function (`Record([]Value) error`) it's impossible to interpret the error: we don't know if it represents a partial or total failure, how much progress was made, etc. This makes it impossible for the metric manager to correctly construct a response code from a metric adapter. We need to refine how errors are returned from adapters, especially when we have APIs whose return shape doesn't match their input shape.

**Comment by ZackButcher** [comment]
To be clear, this issue is about the larger problem of communicating partial failures given that our internal APIs are structured to make batching easy (metrics aspect taking `[]Value` rather than `Value` as a parameter, for example).

**Comment by geeknoid** [comment]
Addressed by new adapter model.
