### ISSUE TITLE
Add a statusz style http endpoint to the mixer

### ISSUE THREAD

**Issue by ZackButcher** [istio/mixer#267]
We should have the mixer expose a human-readable `statusz` page which contains at least
- the current configuration being used to serve requests (full body + SHA fingerprint we use for caching)
- the set of adapters this mixer instance knows about

There are likely other pieces of info we'd like to add to such a page. This page can also serve as our health-check endpoint. In the long term it'd be nice if we came up with a system that allowed adapters to push some info into this page too.

**Comment by kyessenov** [comment]
Are you sure you want to serve the entire config as a health endpoint?
Maybe some version space? Or a timestamp?

**Comment by ZackButcher** [comment]
It's not necessary that it be the health endpoint, just a thought since we'll need some health endpoint in the future anyway. The health page can just serve the hash of the config (which we cache). The main point is having a human readable spot where I can see the config its serving with. The added benefit that I can use the same page to make sure things are up in running during development is nice too.

**Comment by kyessenov** [comment]
That's the kind of things that mixer manager should be doing. Hash of the global config is not very useful since it's opaque. Status should be reported per config unit (selector-aspect pair) imho.

**Comment by ZackButcher** [comment]
Health checks are not the primary purpose of this proposed page, it was merely an observation that a status page could be used to provide health checks until we decide how we want to handle health checks. 

Ignoring anything about health checks, it is still valuable to expose the full configuration the mixer is serving with at any given time, if for nothing else than to be used during development.

**Comment by geeknoid** [comment]
#1495 is replacing this issue.
