### ISSUE TITLE
Establish schema for "well-known" attributes

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#27]
Tracking issue: Per discussions related to #22, there is a desire to have a minimal schema for a set of well-known `attribute` that can be leveraged in configs, etc.

**Comment by douglas-reid** [comment]
Initial PR in #34.

**Comment by mandarjog** [comment]
@ZackButcher I think this is considered done now. Can you reference the issue and close it.

**Comment by ZackButcher** [comment]
Does this cover the attribute manifest we want from the proxy too, or just the descriptor work I've been plumbing? If it's just the second then we can close it with the PR to [istio/api](https://github.com/istio/api/pull/65) that added attribute descriptors to the global config, or the PR to [istio/istio](https://github.com/istio/istio/pull/92) that documented the canonical attributes, I suppose.
