### ISSUE TITLE
Create new adapter instances when config is loaded rather than at request time

### ISSUE THREAD

**Issue by ZackButcher** [istio/mixer#272]
Today the mixer doesn't create adapter instances until the server receives a request. This means that in a running mixer instance when the config is reloaded some request "loses" and pays the latency cost of us doing all the work to initialize every adapter with the new config before we respond to the request. Aside from causing widely varying latencies, this is annoying in adapter implementations whose `NewMetricsAspect` func has side effects. For example, the prometheus adapter creates an http server one time for the life of the mixer, but performs this in `NewMetricsAspect`; as a result that http server is not started until the mixer receives a request.

Instead, when we ingest a new configuration we should create all of the new adapter instances we need outside of a request thread and start serving with the new instances when construction of all of them is completed.

**Comment by guptasu** [comment]
@geeknoid @ZackButcher  can we close this since the new model creates adapters during the config load time.

**Comment by douglas-reid** [comment]
Let's not close this until we are on the new model entirely.
