### ISSUE TITLE
Use an uniform tagging system across all docker istio images (manager, mixer, proxy)

### ISSUE THREAD

**Issue by andraxylia** [istio/mixer#276]
Build system (jenkins/travis) applies:

1.  "date+build#" , where date is YYYY-MM-DD-HH:SS ; required on all images
      - date is a must giving Bazel build produces incorrect date
      - build# - keep in mind that Mixer is on travis, manager + proxy + app (runtime) are on Jenkins

2.  short SHA - required on all images
      github search repo with short SHA will find the commit directly, no need to go to the build system as an extra step

3.  "latest":  to be used only by the build system, only if we apply it explicitly and force it with any new push, otherwise we fall in this trap http://container-solutions.com/docker-latest-confusion/
only one image per repo will have this label

4.  "alpha-XX.XX" 
optional, same label used for all repos, so we can select a matching set of images
can become beta etc.

5.  "release-XX.XX" for when time comes :)

Private builds:

1.  username + date , where date is YYYY-MM-DD-HH:SS - this will help clean up stale images

For all types of builds, additional manual labels are permitted, for instance "demo", "featureX-working". There is virtually no penalty for using multiple labels on an image.

**Comment by douglas-reid** [comment]
Mixer (via travis) already handles (1) and (3).  However, mixer's date stamp does not include "HH:SS".  Adding SHA should be straightforward with travis environment variables.

**Comment by mandarjog** [comment]
@ayj Is this still outstanding ?

**Comment by ayj** [comment]
This is done for #1 - #3. I think #4 and #5 would come later after release qualification is ready. 

cc @sebastienvas

**Comment by sebastienvas** [comment]
We removed date + build as it is impossible to map back to a commit. latest as some issue so at the end we have 
SHA for CI build and X.Y.Z for release.
Dev build are created in gcr.io/istio-testing, Release are created in docker.io/istio
