### ISSUE TITLE
Design and implement support for attribute manifests.

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#304]
We need to have end-to-end support for attribute producers to publish a manifest of the attributes they produce (an array of AttributeDescriptor messages), and then have the rest of the system leverage this manifest for error checking.

Submitting configs that use attributes not present in the current deployment's manifest should produce an error for the user. Similarly, the descriptors specify the types of each attribute so we should produce errors when attribute types are mishandled in the config.

At runtime, since the various Istio components can be built independently and versioned independently, we need to understand and specify what happens when unknown attributes are produced and/or consumed.

**Comment by ZackButcher** [comment]
Implemented in https://github.com/istio/api/pull/73.

**Comment by ZackButcher** [comment]
@geeknoid is there a larger scope to this issue, or does the message definition in istio/api and plumbing in the mixer (https://github.com/istio/mixer/pull/538) cover this?

**Comment by geeknoid** [comment]
I think what we have now is a reasonable first cut.
