### ISSUE TITLE
Need to support no attribute context

### ISSUE THREAD

**Issue by qiwzhang** [istio/mixer#313]
Should not force mixer client to support attribute delta update with attribute context.  attribute_context = 0 in https://github.com/istio/api/blob/master/mixer/v1/attributes.proto#L84  can be used to indicate no attribute context.   All attributes are in the request, no carry over from previous requests

**Comment by geeknoid** [comment]
This effect can be achieved by setting reset_context to true in each request. So I don't think we need anything new here.
