### ISSUE TITLE
Add initial opentracing integration

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#33]
Tracking issue for initial [opentracing](http://opentracing.io/) integration.

It should be possible to create a grpc middleware to add spans for Check requests, etc.  Something like the [grpc-go-middleware](https://github.com/mwitkow/go-grpc-middleware) should suffice.

**Comment by ZackButcher** [comment]
Some notes from preliminary investigation:

- As far as I can tell gRPC does not offer a hook to intercept individual requests/responses in a stream. gRPC's stream interceptor bookends the entire stream, not each message sent/received. This means they're not particularly useful for us other than setting up a root span that represents the lifetime of the entire stream. Instead we'll have to do book keeping in the [grpcServer's streamLoop method](https://github.com/istio/mixer/blob/master/pkg/api/grpcServer.go#L145).

- The current [golang gRPC opentracing impl, otgrpc,](https://github.com/grpc-ecosystem/grpc-opentracing/tree/master/go/otgrpc) ignores streams. Ideally they'll accept a PR to extract the core opentracing logic ([extracting propagated spans, initializing the request's span](https://github.com/grpc-ecosystem/grpc-opentracing/blob/master/go/otgrpc/server.go#L36-L56)), which we can use. This should make it easier down the road if/when they support streams (it'll require gRPC implementing more hooks into streaming RPCs, ideally a per-message interceptor). It also means we can reuse their [options](https://github.com/grpc-ecosystem/grpc-opentracing/blob/master/go/otgrpc/options.go#L5-L18) and [decorator](https://github.com/grpc-ecosystem/grpc-opentracing/blob/master/go/otgrpc/options.go#L20-L34).

- We'll need some way for users to specify which requests to trace, and what properties on the request that should be added to the trace's context. [otgrpc](https://github.com/grpc-ecosystem/grpc-opentracing/tree/master/go/otgrpc) supports some of this already.

- Opentracing propagates info between client and server on every request in almost the same way Istio propagates attributes. There is significant overlap between the info we'll be passing in attributes and the information many tracers pass. It seems likely that we'll want implement an Istio specific tracer on top of our attribute system to get efficiency wins (we'd then need to write adapters that exports traces to known backends). This is out of scope for the initial implementation in Istio, but worth thinking about down the line.

**Comment by douglas-reid** [comment]
@ZackButcher can you add detail on the following bits of functionality we targeted for work and our status?

Tracing support areas:
- Latency Tracing
- Functional Tracing
- Trace Propagation

I believe that we can now, via tracing, report on mixer request/response latency and functional calls. It seems like the remaining work is on propagation. 

Is that accurate?

**Comment by ZackButcher** [comment]
I have a PR in the works for propagation that I expect to get out tomorrow.

We definitely get latency tracing out of the existing infrastructure, but I'm not sure we have the functional tracing we want: right now we only record receives/sends in the server's stream loop, we don't record any information about the flow of the request through the server. I think it'll be fairly easy to add after we get the server wired up: in the dispatch loop where we call the manager to execute a particular adapter we can add tracing information about the adapter we're dispatching to.

**Comment by douglas-reid** [comment]
@ZackButcher should we close this issue (and open another for Stackdriver tracing integration)?  If not, can you provide a short summary of status?

**Comment by ZackButcher** [comment]
Ah, we have duplicate issues floating around: there was another different issue about tracing that I closed yesterday. Yes, we should close this and open another for other integrations.
