### ISSUE TITLE
Review metric schema in context of other OSS projects

### ISSUE THREAD

**Issue by louiscryan** [istio/mixer#37]
Worthwhile to look at concepts in other systems to see how we map. Please add more here ....

Prometheus
https://github.com/prometheus/client_model/blob/086fe7ca28bde6cec2acd5223423c1475a362858/metrics.proto#L76-%20%20L81

New Relic
attributes: https://docs.newrelic.com/docs/agents/manage-apm-agents/agent-data/collect-custom-attributes
metrics: https://docs.newrelic.com/docs/agents/manage-apm-agents/agent-data/custom-metrics
well-known attributes: https://docs.newrelic.com/docs/insights/new-relic-insights/decorating-events/insights-attributes

AppDynamics:
custom metrics: https://docs.appdynamics.com/display/PRO42/Analytics+Events+API
well known attributes: https://docs.appdynamics.com/display/PRO42/Transaction+Analytics+Data

DynaTrace:
well-known attributes: https://community.dynatrace.com/community/display/APMSAASDOC/Data+Models+for+REST+API+Payloads

**Comment by douglas-reid** [comment]
Statsd: https://github.com/etsy/statsd/blob/master/docs/metric_types.md

**Comment by douglas-reid** [comment]
Also worth considering:

- AWS CloudWatch
  - Custom Metrics: http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html
  - Well-known metrics and dimensions: http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CW_Support_For_AWS.html

**Comment by wora** [comment]
Stackdriver Monitoring will publish its API metrics soon. Please consider it as well.

**Comment by curlup** [comment]
Please consider also
http://metrics20.org/

and https://github.com/vimeo/carbon-tagger

**Comment by geeknoid** [comment]
Zack, do we need to do anything specific here?

**Comment by ZackButcher** [comment]
Given our decisions around descriptors where we punt to adapter config to handle backend representation (so our representation of a metric in Istio is just a value and dimensions, nothing else) I think we're fine on this front.
