### ISSUE TITLE
Evaluate the use of a full-fledged language for attribute pattern matching.

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#387]
We want to evaluate whether it is possible to use a full-fledged programming language to implement the logic that pattern matches against attributes and generates calls into configured aspects.

The idea is that we would use a jitted language for this purpose for max perf. The operator would write in this language directly to get fully customized power-user kind of behavior. The operator could also write using a higher-level config-style environment, which we would translate into the language automatically, run the jit on, and then use at runtime.

We need to experiment and see if using a general-programming language makes sense, whether we can efficiently generate correct programs, etc. We'll prototype using the otto JavaScript interpreter since it's super easy to use and interoperate with. In the long run, if we like JavaScript we could use v8. However, JavaScript is not ideal for operators, we'd probably be better off with a Python environment. Depends on what JITs exist out there in OSS...

**Comment by ayj** [comment]
Is it worth considering cgo calling overhead in this evaluation? It looks like no-op cgo call in golang 1.8 is ~50ns (ref https://go-review.googlesource.com/c/30080/) 

ref https://github.com/golang/go/issues/16051

**Comment by geeknoid** [comment]
Two comments on that front:

- I expect to have a fairly chunky model. There would be a single transition into the jitted code per incoming request.

- If that's still too much overhead, then the jitted code can likely be made to run in a stand-alone thread and interacted with via some IPC scheme, so there would indeed be no entering/exiting costs. There would be a context switch cost of course though.

When evaluating the doability of this, we need to definitely look at the end-to-end cost and make sure we're happy before jumping.

**Comment by wora** [comment]
If we do this, we should design a super simple language that can be trivially compiled to 50% of C speed, then we can use it to replace for most of business logics.

https://lwn.net/Articles/713918/

This is user space network stack written in Lua. The team claim to support 100Gbs network this year. Our new language must be able to perform at the same level. I will be happy to contribute to this effort.

**Comment by geeknoid** [comment]
All done.
