### ISSUE TITLE
Commit b83d5b2 breaks traffic flow for echo app

### ISSUE THREAD

**Issue by andraxylia** [istio/mixer#403]
Mixer image from docker labeled 2017-03-17-18.02.40 allows the traffic to pass; latest images gives 503 code

None of the newer mixer images open port 42422, although there are no errors in the logs.

**Comment by douglas-reid** [comment]
@geeknoid can you please take a look at what is happening here?

**Comment by geeknoid** [comment]
Zack, I think you have more context than me on this...

**Comment by geeknoid** [comment]
Oh, it's attribute-related. I'll take a look.

**Comment by geeknoid** [comment]
Turns out this broke when I pushed in the OOO return functionality. It's a state capture problem around spawning goroutines. I'll have a PR out tonight with appropriate fixes.

**Comment by andraxylia** [comment]
There is another problem with metrics for 42422 not being available. Can this be related?

**Comment by douglas-reid** [comment]
I don't think it is related. @ZackButcher something is wrong with the configuration of logs aspects in testdata/serviceconfig.yml.
