### ISSUE TITLE
Create an Adapter Developers' Guide

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#419]
How to create, integrate, debug adapters.

Should live in istio/istio repo.

**Comment by elevran** [comment]
@ZackButcher following up on call - can you please do a quick dump of your notes regarding adapter guide? Nothing fancy, just to help drive the outline and have some place for us to start filling in data.

**Comment by sakshigoel12** [comment]
@guptasu said he is working on markdown. ETA tomorrow.

**Comment by guptasu** [comment]
PR out https://github.com/istio/mixer/pull/1379
