### ISSUE TITLE
Create a Mixer Operators' Guide

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#420]
Describe how to deploy, configure, and manage the mixer.

**Comment by douglas-reid** [comment]
Is this still a thing? Or has it been replaced by the various assigned Tasks, etc.?

**Comment by geeknoid** [comment]
I still think it's a thing, but clearly we haven't been working on it...

**Comment by mandarjog** [comment]
@geeknoid this part https://istio.io/docs/concepts/policy-and-control/mixer-config.html#aspects  explains the configuration building blocks. 
Are you thinking something like https://istio.io/docs/concepts/traffic-management/rules-configuration.html ?

**Comment by geeknoid** [comment]
Yes, something like that.

mixer-config explains the architecture, it's not intended to show users the
step-by-step stuff they need to do, the exact meaning of each field, etc.
We don't provide enough information at this point for users to actually set
things up and configure the system.

**Comment by mandarjog** [comment]
We have all the requested information covered in several docs.
It is can either be a task or a concept per our doc structure. 

1. Abstract and long discussion about Mixer configuration in /concepts/policy-and-control/mixer-config.html
2. Specific tasks in /tasks
3. We are missing a lower level view of how to configure an aspect and associated items, which https://github.com/istio/istio.github.io/pull/125 attempts to provide.
