### ISSUE TITLE
Support mixer versioning

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#424]
We need to make it easy for folks to figure out what they're running. So:

- We should generate a version.go file as part of the build which includes the SHA of the latest commit as a const. Perhaps a date string would be handy too.

- When the mixer starts, it should pump its version info (taken from version.go) into its logs.

- mixs should have a 'version' command that prints out the version info.

- We could also consider adding a Version API call to the mixer which returns the version info, and then we could add a version command to mixc to report the version of a running instance.

**Comment by mandarjog** [comment]
This is similar to what manager does. We would like to use a common approach.
https://github.com/istio/manager/tree/master/cmd/version

**Comment by geeknoid** [comment]
Anything else to do here?

**Comment by douglas-reid** [comment]
No. I think this is closable now.
