### ISSUE TITLE
Mixer Config API (alpha scope)

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#445]
Implement mixer config API.
https://docs.google.com/document/d/17Ww_wS72UvGa15WipUibyLetlLNjK3hnqi-DfhkpoMg/edit#

Part Ia.  Mixer
1. Import a file and send in a series of calls
2. Update parts of the config thru the API
3. Basic over rides
4. Update config access in mixer to read from the KV store

Part 1b. istioctl
1. Update istoctl to use mixer config API.  --> details to follow

Part II. (beta)
1. auth
2. multiple scopes

**Comment by kyessenov** [comment]
Please file a bug into appropriate repo (manager?) and link here. It's not clear to me what the action items are based on the issue description.

**Comment by geeknoid** [comment]
Can this issue be closed?

**Comment by douglas-reid** [comment]
echoing @geeknoid, do we feel that the current functionality is sufficient for alpha (and can we close)? If not, what remaining work needs to be tackled for alpha?

**Comment by mandarjog** [comment]
We are done with alpha scope work for this.
