### ISSUE TITLE
Add a mock redis in go for testing purpose.

### ISSUE THREAD

**Issue by chowchow316** [istio/mixer#463]
As discussed in #435,  a mock redis in go is quite helpful for testing purpose, for both redis quota adapter and config value store. And there are already open-sourced implementations, for example: https://github.com/alicebob/miniredis

**Comment by chowchow316** [comment]
Imported miniredis in unit tests for redis quota adapter.

**Comment by chowchow316** [comment]
Reopen this since the mock redis did not implement the timeout function for keys, so expiring keys can not be fully tested here.

**Comment by chowchow316** [comment]
Added timeout in miniredis. Expiring keys can be covered in unit test now. But the code coverage is < 80%, needs to be improved.

**Comment by chowchow316** [comment]
#537

**Comment by cmluciano** [comment]
#537 is merged so this issue can probably be closed

**Comment by geeknoid** [comment]
Tracked by Galley work items.
