### ISSUE TITLE
Define an adapter model to support attribute injection on the mixer.

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#475]
We just discussed this. General idea is:

- We'll introduce a new aspect kind for attribute injection.

- We'll extend the manager inventory to include a list of attibute injectors (the inventory currently has CheckManagers, ReportManagers, and QuotaManagers, now it'll gain InjectionManagers)

- We'll change the adapter manager to synchronously invoke injection aspects prior to invoking check/report/quota aspects.

**Comment by douglas-reid** [comment]
Closing this, as we have basic functionality in the mixer codebase yet.
