### ISSUE TITLE
Ensure all uses of ConfigError are using correct field names.

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#512]
We need to make sure the field names supplied to the ConfigError type throughout the mixer are the field names experienced by the YAML author and not the Go canonicalization of those names.

Without this, error messages won't make sense for the YAML author.

**Comment by kyessenov** [comment]
proto parser is lenient to whether you use proto-case (my_field) or go-case (myField)

**Comment by geeknoid** [comment]
Indeed. But we'll be documenting just one of these names and I want the names produced by the errors to match the names in the docs.

**Comment by ZackButcher** [comment]
In aspect validation I used the name of the generated field; in most cases for our config fields proto field name matches golang struct field name, barring capitalization (proto's `labels` becomes `Labels` in go). The only fields that come to mind as very different between the two are proto's `descriptor_name` (we'd use `DescriptorName`, but today there's no validation for that field anywhere), and `template_expressions` which is used in two places and gets the `ConfigErrors` field name of `TemplateExpressions`.

I think we should document the proto field names: our automated doc gen will document the proto field, and I think it causes the least cognitive dissonance for a user trying to configure the system (I use exactly the name in the proto file, and receive errors about that field; no mental translation required).

**Comment by douglas-reid** [comment]
Any update here?

**Comment by geeknoid** [comment]
Nope, I'll be taking care of this soon unless someone beats me to it.
