### ISSUE TITLE
Determine how to populate monitored resources and security principals at runtime

### ISSUE THREAD

**Issue by ZackButcher** [istio/mixer#515]
Our configuration defines descriptors for [monitored resources](https://github.com/istio/api/blob/master/mixer/v1/config/descriptor/monitored_resource_descriptor.proto) and [security principals](https://github.com/istio/api/blob/master/mixer/v1/config/descriptor/principal_descriptor.proto), but we don't actually wire them through the mixer. We allow the user to define descriptors in the global config, but we don't have any way to write expressions so that we can construct monitored resources and principals at runtime. We need to think about how this flows through the system.

**Comment by douglas-reid** [comment]
FWIW: monitored resources might be something that is GCP-specific, and can be configured via GCP adapter config

**Comment by ZackButcher** [comment]
Stackdriver's API uses them, and is not GCP specific - I _think_ there are usecases outside of GCP, though I'd probably take the best that they're used mainly in GCP.

**Comment by geeknoid** [comment]
Zack, should we close this given the new adapter model?

**Comment by ZackButcher** [comment]
Yes, per new adapter model, defining principles/MRs should be the domain of the adapter. The hard part is that those objects likely require evaluating additional expressions at runtime, but adapters don't have a way to request evaluation other than at the constructor/instance level.

This could be solved via Attributes adapters, but forcing double configuration or writing two adapters sucks. I think we might be able to get away with a generic Attributes adapter for MRs and a second for Principles that injects them into the request context for usage by downstream adapters. (I actually like this idea quite a bit.)

**Comment by douglas-reid** [comment]
We still have the option of creating a new template that has a MR and/or Principle submessage, right?

Also, instead of a new adapter, you might consider having an adapter that needs MRs be both an Attributes adapter and a Report adapter. That /was/ previously possible (and might allow you to work around trying pass state through attributes).

**Comment by ZackButcher** [comment]
Adapters should be able to be both, but the gain there is minimal compares to just having two separate adapters, I think: you still need to configure both the attributes half of the adapter and the half consuming the MRs/principles. At that point I don't think you're saving any config, maybe just an `adapter` stanza.

**Comment by ZackButcher** [comment]
With the advantage that if its separate then their output could be depended on by many different adapter impls, where if e.g. Stackdriver was an Attributes adapter producing its MRs, I wouldn't want to depend on those MRs in any other adapter.

**Comment by douglas-reid** [comment]
It seems to me that if MRs are going to be used by other adapters, and depend on attribute expressions, they should be part of a template (or reused in multiple templates).

But if they are only going to be used in SD, creating a shortcut _might_ be easier than passing around a string_map attribute or whatever.

**Comment by ZackButcher** [comment]
I guess my argument boils down to: I think an Attributes adapter producing e.g. a STRING_MAP from a set of expressions at runtime is generally useful, even outside of the scope of MRs/Principals, and it can then be used to implement supplying MRs at runtime.

**Comment by geeknoid** [comment]
As a side-note, we should always keep in mind that we can extend the
attribute type system if we need to. We can enable attributes to carry
richer types if we want.

**Comment by douglas-reid** [comment]
Having an APA producing a STRING_MAP is totally fine.  But there is nothing that needs to be done to support that other than writing adapters that produce STRING_MAP -- the functionality already exists. 

There still remains the issue of how to pass the derived attribute back in via constructor. Would this new attribute be a 'dimension' on the Instance?  Or would we make it a new field in the template?  That is really more what I'm trying to figure out. It _feels_ like if we add a new field, we could avoid the need for any other adapter.

**Comment by ZackButcher** [comment]
In new adapter model we're adding these fields to templates where they're required. See https://github.com/istio/mixer/pull/1163
