### ISSUE TITLE
Proposal: attributes as first-class concept of Istio

### ISSUE THREAD

**Issue by wora** [istio/mixer#52]
I would like to propose to define **attributes** as a first-class concept of Istio at the same level of proxy, mixer, adapter and others, and use it to connect many sub-systems together, such as billing, logging, monitoring, analytics.

The main reason to define attributes as a first-class concept instead of part of proxy or mixer is to establish a stable foundation that we can quickly build many components on top it, including proxy, chemist, logging, monitoring, billing, rate limiting and more. So we don't let one component overrule others. Istio ecosystem must interact with many other systems, including standards like HTTP, gRPC, REST, Swagger/OpenAPI. With first-class attributes, we can develop the system as N modules instead of (N * N) mesh. Per our experience with Google API Platform, I am confident this proposal is significantly better and simpler than previous metadata designs and should meet Istio's needs comfortably.

An Istio attribute is a piece of metadata describing activities with an Istio service, such as the `origin.ip` (the attribute) of an API request (the activity) received by an Istio API service. Being a first-class concept, the same attribute will have the same value and semantics across all sub-systems, e.g. `origin.ip` in the logs will mean the same thing in the rate limiting system. If you want to allow one request per IP address per second, you can define the rate limit as "1/{origin.ip}/s".

The schema of the attribute will be simple:
- **name:** Each attribute has a qualified name. The namespace will be organized as "organization.product.property".
  - For example, `origin.ip`.
- **type:** Each attribute has a type, which specifies the value type. The type will be defined by an enum type.
  - For example, `STRING`.
- **value:** Each attribute has a string value, which **must** be interpreted according to the type.
  - For example, `127.0.0.1`.

To define the above scheme using proto3, it would look like this:

package istio.type;

message Attribute {
  enum Type {
    // The value is a valid UTF-8 string.
    STRING = 0;
    // The value is a 64-bit integer printed as a decimal number text. It must not have leading "+".
    INT = 1;
    // The value is a 64-bit floating point printed as text.
    FLOAT = 2;
    // The value is a timestamp with RTC 3339 format.
    TIMETAMP = 3;
  }
  string name = 1;
  // Most attributes have well known type, so this field is often omitted.
  Type type = 2;
  string value = 3;
};

The attribute can be used in various systems. For example:
- To log attributes about an API request, we can simply specify a list of attribute names in the logging config.
- To monitor a system against certain attributes, we can use attributes as dimensions of metrics.
- To specify rate limits, we can use attributes in the limits.
  - Example: "1/{origin.ip}/s" and "3/{origin.user}/min".
- To control access, we can use attributes in access policy.
  - Example: origin.user != null.
- To express simple resource ownership.
  - Example: origin.user == resource.owner. 
- To send attributes from proxy to REST servers, we can map attribute to HTTP header.
  - Example: origin.ip => X-Origin-IP

Thoughts?

**Comment by mandarjog** [comment]
- Can you provide rationale for why value is untyped? ( a string?)
- is this only definition of type? Or we will actually define standard vocabulary like '''src.ip'''

**Comment by wora** [comment]
We did extensive study with labels, see https://github.com/googleapis/googleapis/blob/master/google/api/label.proto, and we use it for logging, monitoring, billing just like attributes. In practice, most of values are strings, integers can be quickly converted to/from strings, other value types are much less used.

If we use strongly typed oneof, you have to mentally remember which attribute uses which type. This is a huge burden and error prone. Try to print the attribute to console or generate a hash key or copy the value from a to b, you will find 2/3 of your code are dealing with oneof. Now if you want to write an UI editor for attributes, there is no way for the UI to know how to save input "123" into the oneof field. I spent a lot of time on this and eventually led to Google API labels dropping the type.

There is only one type definition, because many components (proxy, mixer, policy engine) need to operate on attributes, and they can only handle small set of types. We can consider attributes as primitive types for our configuration language. In any language, the number of primitive types is very limited, and generally fixed. Even so, it takes a lot of time to build a language runtime.

Regarding standard vocabulary, yes, Istio will define a standard set of attributes like "origin.ip". Almost all services will be happy with just the standard set. Google has hundreds of public API services, we have plenty experience to believe it. However, any company is free to introduce their own attributes. Istio will provide good support for them as well.

**Comment by douglas-reid** [comment]
Can we close this now, with the istio/api repo and the PR for adding Attributes there?

**Comment by douglas-reid** [comment]
Closing this issue, as I believe the top-level concern has been addressed.
