### ISSUE TITLE
Rename tools to tool

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#530]
In order to keep with our own conventions, we should use singular names for directories.  https://github.com/istio/mixer/blob/master/doc/dev/conventions.md#directory-and-file-conventions

**Comment by kyessenov** [comment]
This is bazel convention. I protested against it too ;)

**Comment by sebastienvas** [comment]
https://bazel.build/versions/master/docs/bazel-user-manual.html. We can t rename.

**Comment by douglas-reid** [comment]
sigh.
