### ISSUE TITLE
Improve adapter configuration story re: attribute generation

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#534]
Tracking bug:

At some point in the near future, we need to add the following capabilities:

- type-checking on inputs to Generate (perhaps figure out how to wire in populated struct of inputs, etc.)
- type-checking on outputs from Generate (perhaps pass in AttributeDefinitions for controlling outputs, etc.)
- validation that generation of an attribute value is not occurring in multiple places (proxy-mixer, mixer APAs, etc.)

When we are ready to tackle this issue, separate issues should be filed an assigned for the subtasks.

**Comment by geeknoid** [comment]
Please close if this is fully redundant with your ongoing APA work.

**Comment by guptasu** [comment]
@geeknoid this bug can now be closed since the sub items are already covered by #1518 and #1477

**Comment by guptasu** [comment]
@douglas-reid FYI
