### ISSUE TITLE
Mixer + Proxy integration test

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#539]
Mixer and Proxy should have an integration test that exercises an verifies a few features.

1. Ratelimit
2. Metrics -- verification using prometheus backend. 
3. k8s pod info attributes generation

**Comment by mandarjog** [comment]
This is being done in an end to end test.

https://github.com/istio/istio/blob/master/tests/kubeTest.sh#L214
We generate load on the cluster using wrk and metrics are being fetched.
We need to apply rate limits between those calls to wrk and verify that fetched metrics look correct.

**Comment by douglas-reid** [comment]
we have basic integration tests now that exercise a few mixer aspects / features. these include:
- rate-limiting
- denials
- adding new metrics

They run with the k8s attribute generation preprocess adapter enabled (though they do not currently validate output from that attribute generator).

There is some obvious work that can beef them up (adding prometheus to the deployment and verifying metrics via promql as opposed to from /metrics, checking the source and target dimensions more carefully for metrics to verify correct k8s attribute generation, etc.).

That being said, can we close this for alpha and file a different issue for enhancing integration testing?
