### ISSUE TITLE
Rethink the "kind" property when configuring adapters.

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#542]
The only reason we require the user to specify the "kind" field when configuring an adapter is that we have support in the mixer for a single named adapter to be used by different aspect kinds.

I propose that we simplify this and require individual registered adapters to only support a single aspect kind. If a single chunk of code in pkg/adapter wants to be usable by multiple aspet kinds, it would need to register distinct builders, each with a unique name.

Considering this multi-headed adapter story is marginal at best, I'd rather simplify the concepts the operator has to contend with.

**Comment by mandarjog** [comment]
In issue #204 this was deemed necessary to include this support.

This is exactly what we had before, "kind" attribute was informational.
Let us make sure we really want to go back there.

**Comment by geeknoid** [comment]
I think we went too far. We should support a single adapter exposing multiple builders, yes. But each should have a separate name so it is unambiguous without needing to be qualified by "kind".

I'm writing the config doc, and starting with the most basic concept of defining blocks of adapter configuration. Even though this is the most basic thing, I have to have a forward reference to aspects and aspect kinds to explain this field.

**Comment by mandarjog** [comment]
Consider the case of a potential gcp provider that provides metrics and logging back ends.
Having single kind per adapter forces us to repeat connection+credential info.

**Comment by geeknoid** [comment]
OK, that's a valid point.

Given that then, should the config field actually be called "kinds" and take an array of kinds? Otherwise, how do you in fact achieve sharing of credentials as you mention?

**Comment by ZackButcher** [comment]
I like changing the `string kind` field to `repeated string kinds`; I think it's the easiest way to achieve what we want (single adapter config no matter how many aspects it exposes).

**Comment by mandarjog** [comment]
1. Adapter registers itself as several `kinds`like it does today.
2. kinds needs to be `map [string]string    Kind --> adapterName`

This way be *do share* connection info, but you are still free to name adapter independently .
In the GCP example above, you may not want to name all `kinds` provided by `GCP` as defaults.

in that case it will be
`
adapter: gcp
params:
...
kinds:
  metrics: gcp-metrics
  logs: default
```

**Comment by geeknoid** [comment]
I just realized what the real problem is.

The real problem is that even though there is a single adapter in terms of code, we are supporting different config formats for each builder within this adapter. I think this is where the flaw lies.

The config we give to adapters is what I'm calling "operational configuration state". Things like IP addresses, URLs, timeout values, etc. These are details about how this particular adapter behaves. *I contend that these parameters are independent of the builders being used for this adapter.* There's one piece of code there and so there should be a single chunk of config uniformly applied across builders.

So I will replace my original suggestion, and my secondary suggestion with this third suggestion:

- We remove the "kind" field from config. Adapter configuration applies to a whole adapter.

- We reintroduce the notion in code of an Adapter object. This is the thing that will receive config, perform validations.

- Builders are simplified and no longer deal with adapter config, only aspect config. Builders must be given adapter configuration as an input to their Execute method, so they know what config they're being used with.

**Comment by ZackButcher** [comment]
> Builders are simplified and no longer deal with adapter config, only aspect config. Builders must be given adapter configuration as an input to their Execute method

What do you mean by this? Today Builders don't have an execute: they return an aspect which implements the Execute method; they need to ingest adapter config to produce that aspect. Builders use adapter config to produce an aspect-implementing-object, managers use aspect config to marshal runtime values into structures that the aspects understand, and the aspect-implementing-objects themselves never receive config at all.

<hr>

Why can't we do this: drop the `kind` field from adapter config, rely on the registry to determine the `kinds` an adapter exports. We have the registry in hand at config validation time, so no loss of info there. Adapter config can takes in the common params, e.g. consumer API project for a GCP adapter. Then we have an aspect config chunk per aspect exposed by the adapter.

In global config:
```yaml
adapters:
- name: MyGCPAdapter
  params:
    databaseUrl: https://
    otherThingINeed: 5
    stackdriverAccount: 123
```
and in service config:

```yaml
aspects:
- kind: quotas
  adapter: MyGCPAdapter
  params:
    // quota buckets for gcp to enforce
- kind: metrics
  adapter: MyGCPAdapter
  params:
    // metrics to export to SD
- kind: application-logs
  adapter: MyGCPAdapter
  params:
    // monitored resources and log templates
```

As long as there's no repeated `(kind, adapter)` pairs in aspect config I think everything should Just Work™ with our existing config ingestion/validation code. Only update required is to use the registry during validation. Looking at the registry code as implemented today, [it already computes the kinds a builder exposes via the register methods it calls](https://github.com/istio/mixer/blob/master/pkg/adapterManager/registry.go#L131), not using its adapter config.

**Comment by geeknoid** [comment]
The approach you suggest cannot work. Right now, a single adapter can expose different builders, and each builder can have its own config. So right now, you need to say "adapter X, kind Y" in order to figure out which config format to use.

Let me restate what I was trying to say above.

I want us to introduce an explicit Adapter object. This is the thing that will be config given to it. The adapter should be called in order to retrieve its builders. The builders in turn are called to get configured aspects.

**Comment by mandarjog** [comment]
closely related to or same as issue #337

**Comment by douglas-reid** [comment]
Do we ever expect that the builders would be provided different config, based on the aspect implementation they are building? I'm having a hard time figuring out what the use case for that would be.

the stdioLogger implementation we have right now is the only adapter we have that implements two aspects -- and the default config it uses is passed to both builders.

**Comment by geeknoid** [comment]
The point is that architecturally, they are not tied together and so they
could have different types of config. I want to tie those together
explicitly so that an adapter gets a single chunk of config state.

**Comment by geeknoid** [comment]
No longer relevant with new model.
