### ISSUE TITLE
Clearly split config-time and request-time code in the mixer framework

### ISSUE THREAD

**Issue by ZackButcher** [istio/mixer#550]
Today there are two distinct code paths in the mixer:
- request time, where adapters are executed according to config
- config time, where we ingest and validate the configuration the user provided

These two code paths are distinct and do not interact. (The sole touch point in the mixer between the code paths two is in the `adapterManager/manager` class, which has a reference that's atomically updated to the latest config at the end of the config time code path.) Further, these two paths have very different requirements. In the request path we try to avoid allocations and optimize for low latency. In the config path we don't really care about latency or allocations and instead optimize for understandability (for maintainers) and good error messaging for the operator.

The problem today is that these two code paths are intermixed; this will almost certainly lead to pain down the line where we (or a third party adapter author) introduce high latency, allocation-full code to the request path unintentionally because of the lack of delineation between the two.

## Proposal

We should clearly split the two code paths:
1. in `//pkg/aspect`, every manager implements the `config.AspectValidator` interface; this implementation has aspect specific logic but is completely unrelated to any other code in each aspect manager. These implementations should be moved into `//pkg/config`.
    - as a side effect of this the aspect parameters, defined in `//pkg/aspect/config/<aspect name>.proto` today, should be migrated to `//pkg/config/proto/<aspect name>.proto`
    - descriptor validation is not yet implemented; we're planning on implementing it as part of aspect validation. Under this proposal, it would also be implemented in `//pkg/config` too, likely in `//pkg/config/descriptors`, separating the concerns of descriptor validation from aspect param validation.
2. `//pkg/adapter` defines the `adapter.ConfigValidator` interface then embeds it in the `adapter.Builder` interface. The `adapter.ConfigValidator` interface should be split (so that `adapter.Builder` can still provide a default config) and removed from the `adapter.Builder` interface. Instead, we should require that adapter authors give us three things: a builder, an aspect implementation, and a config validator. (Today they give us a build and an aspect implementation.)

(I'm very convinced 1. needs to happen, I'm still thinking through 2. and how warranted it is.)

After these changes the two code paths will be very clearly split: mixer framework validation all lives in `//pkg/config` and adapter validation lives in a separate struct than the runtime adapter logic. Anything outside of `//pkg/config` must be written to the standards of request path code, and anything in `//pkg/config` can be implemented with more lax standards.

**Comment by ZackButcher** [comment]
@geeknoid @guptasu @mandarjog @douglas-reid Thoughts on this? (I guess an @ mention is a better way to notify than assigning the issue.)

**Comment by geeknoid** [comment]
I like the overall approach. I've been worried about these blurred lines for a while, but never had a clear plan on how to address it.

This intersects with two other ideas I've been discussing:

- I think the configs from pkg/aspect/config should move to the istio/api repo and integrated directly in the AspectConfig struct.

- I want to get rid of the adapter.kind field from config. This requires introducing a new object in adapter code that represents the adapter as a whole, distinct from builders. We should factor this in as we consider rejiggering things.

**Comment by douglas-reid** [comment]
Does aspect config structure belong in an istio/api repo? It seems like a detail that only mixer ever cares about (and thus is something that can be self-contained -- reducing friction related to adding new ones).

**Comment by geeknoid** [comment]
I think the shape of aspect config should be considered part of our API,
since callers can program against the APIs and use those protos.

**Comment by ZackButcher** [comment]
We have not done what this issue proposes: there is still code that deals with config out of the request path that lives side-by-side with code in the request path that doesn't deal with config. All of the config validation in pkg/aspect, and in adapters themselves. All of this code should move around.

We probably need to update how exactly we want to structure things in light of the new adapter model, but the core issue persists and has not been resolved.

**Comment by geeknoid** [comment]
Addressed by new adapter model.
