### ISSUE TITLE
Combine access-logs and application-logs aspects

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#560]
We have redundant loggers, we should combine them. The effect of one vs. the other can be achieved entirely through config.

**Comment by douglas-reid** [comment]
We've gone around and around on this several times. At one point, the idea was that we would provide "standard" formats for access logs out-of-the-box to hide the ugliness of the template expressions from operators. We've backed away from that recently with several of the config changes.

**Comment by geeknoid** [comment]
Addressed by new adapter model.
