### ISSUE TITLE
Fix ratelimit issues

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#574]
For alpha, we need a plan to fix the ratelimit interactions with mixer.

Proposed plan:

- hardcode in a name in the mixerclient config (maybe change it from `RequestCount` to `RateLimit`) (see: istio/manager#527)
- add fields to the mixer quota aspect config that allows specification of a limit that should be applied within that scope/subject (DONE - istio/mixer#549)
- remove `max_amount` from the descriptor of `RequestCount`/`RateLimit` (no sense in setting an upper bound on rate limits at this point) (DONE - istio/api#77)
- set `limit: 5` in the aspect config for the selector of "ratings*"

That should allow mixerclient to call `Quota()` on all requests, but have mixer just return `status.OK` unless the quota aspect is configured and linked to the `RateLimit` descriptor for a scope/subject.  And it should allow *different* limits based on scope/subject.

**Comment by geeknoid** [comment]
Do we still need this issue?

**Comment by ZackButcher** [comment]
Yes, it's still broken AFAIK. @mandarjog was running down the latest issue.

**Comment by mandarjog** [comment]
This is done now.
