### ISSUE TITLE
Improve DefaultBuilder pattern to prevent accidental mutation of the 'one true default struct

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#638]
Email thread:

On Thu, Apr 27, 2017 at 3:21 PM, Martin Taillefer <mtail@google.com> wrote:
What's happening is that DefaultConfig is returning a pointer to a singleton global variable. The test proceeds to change this value, so subsequent uses of the function will return this changed value instead of the original default.

For now, the tests should made copies of the default config and use that for their tests.

In the long run, it's probably a good idea for us to change how the DefaultBuilder stuff works such that we're not subject to this kind of problem in the future. Doug? 

On Thu, Apr 27, 2017 at 2:21 PM, Qian Sun <qians@google.com> wrote:
Hi Martin,

I've done some debugging, and find some issue here (in both memQuota and redisQuota), which may be related here.

Specifically, I found that the following line:
c := b.DefaultConfig().(*config.Params)
did not get the default config in https://github.com/istio/mixer/blob/master/adapter/memQuota/memQuota.go#L50 and https://github.com/istio/mixer/blob/master/adapter/redisquota/redisquota.go#L43. Instead, it kept the configuration as in the previous test function...

For example, I set some wrong configuration in TestBagConfig(), and the next test func() will pick this wrong config if I do not specifically modified it to correct.

Do you have any clue of this behavior? Or did I miss anything here?

Best,
Qian

On Wed, Apr 26, 2017 at 5:53 PM, Qian Sun <qians@google.com> wrote:
I see... Working on the comment-out PR now, will send it out soon.

On Wed, Apr 26, 2017 at 5:48 PM, Martin Taillefer <mtail@google.com> wrote:
Redoing my build didn't help... 

On Wed, Apr 26, 2017 at 5:37 PM, Qian Sun <qians@google.com> wrote:
One more thing, I recall there was some issue of rebuild in Jenkins yesterday, I also asked Seb to clean the Jenkins before I do the rebuild. 

I'm not sure whether it is related to this though.

On Wed, Apr 26, 2017 at 5:17 PM, Martin Taillefer <mtail@google.com> wrote:
Thank you.

Sounds like we have a race condition in there somewhere.

I just retried the build on Jenkins, hopefully it'll pass this time around.

On Wed, Apr 26, 2017 at 5:13 PM, Qian Sun <qians@google.com> wrote:
Actually no idea, Doug and I debugged it yesterday, and we could not reproduce it locally either.

But after retried on Jenkins, it worked magically...

I will make a PR to comment out the test case related to this issue. Then try to explore it as deep as I can...

Best,
Qian

On Wed, Apr 26, 2017 at 5:07 PM, Martin Taillefer <mtail@google.com> wrote:
Do you have any ideas why I'm seeing redis test failures in the presubmit tests:

https://testing.istio.io/job/mixer/job/presubmit/737/console

Running the tests locally on my machine works fine.

**Comment by mandarjog** [comment]
DefaultConfig serves dual roles, those need to be broken up. 
1. Return an instance of aspect specific proto so Mixer can fill it in with incoming config.
2. Specify Default values.

(1) instead of using the returned struct as it is, mixer should only use it's type --
 `reflect.New(valType)` like `pkg/config/descriptor.processArray()` does today.

(2) is incomplete as it stands today because the merge operation of defaults and incoming values is left to proto.Unmarshal ().  The aspect manager should do a proper merge in code. 

Default config is still needed for documentation purposes.

**Comment by geeknoid** [comment]
Addressed by new adapter model.
