### ISSUE TITLE
Traffic should be treated as in-cluster after being accepted by the Ingress.

### ISSUE THREAD

**Issue by andraxylia** [istio/mixer#649]
Traffic should be treated as in-cluster after being accepted by the Ingress.
Ingress-proxy should talk with mixer.

**Comment by douglas-reid** [comment]
@esnible let's use this issue to track better Mixer integration with Ingress.

- [ ] The "source" field for traffic that reaches a microservice via the ingress should have the ingress name as the source.
- [ ] Traffic from the outside into the ingress should also appear in Prometheus.
