### ISSUE TITLE
Need to provide a unique id to each adapter instance

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#653]
Mixer needs to provide a unique id to represent each instantiation of an adapter. A good choice for a unique id would be the name of the containing aspect.

The reason for this value is such that when an adapter talks to a backend, it has a way to separate data from different aspects. Otherwise, the distinct data may get collapsed together.

**Comment by ZackButcher** [comment]
We could just reuse the SHA hash of the adapter's config that we already use as the cache key for the adapter instance in the adapterManager (or we could even use the full [`cacheKey`](https://github.com/istio/mixer/blob/master/pkg/adapterManager/manager.go#L369) struct).

**Comment by douglas-reid** [comment]
Can we expand on the problem a little bit?

Does the combination of adapter and aspect config not provide enough details to properly segment data? It feels like it should.

**Comment by geeknoid** [comment]
I think it's preferable to use a human-readable name since in the end this unique id will be used to create new DB columns, or inject new labels in the output, etc. The user will likely see those surface at some point.

This is why I suggest using the aspect name. It is an operator-authored symbol, so seeing it show up will be meaningful to operators.

**Comment by geeknoid** [comment]
@mjog and I discussed this yesterday.

The issues is evident with the redis adapter. If you create multiple
aspects for the adapter, each with similar labels, the redis adapter will
incorrectly combine all the state from these various aspects into a single
set of entries in redis. It can't do otherwise, since each adapter doesn't
have a sense of its own identity. We don't provide it the right info for it
to properly separate data in the backend.

This could potentially be worked around by having different adapter
configurations, each with a magic "key" field. Different aspects would
depend on different adapter config blocks. Or we make this a
natural/invisible part of our system.

**Comment by douglas-reid** [comment]
To me, it feels like it should be a distinct adapter configured differently via operator-supplied config. And, as you state, having different aspects depend on different adapter definitions.

That is certainly the impression I was operating under, based on our configuration model. I'm not convinced that having adapter code depend on aspect names is more natural.

Is your suggestion to have something like:

adapterID: concat(subject, aspectKind, adapterName)

and then to pass that adapterID into the New* factory methods?

How would adapters be modified to do something with this bit of config as distinct from the adapter config they already have (a map from "adapter ID" to say "gcp project ID" in the adapter config, maybe?)?

**Comment by mandarjog** [comment]
This is what I have in the docs. I no longer think we need an "aspectID",
check  how a key is formed.


https://github.com/mandarjog/istio.github.io/blob/e9431a4be68e6f9ab70747bb614ec53dae9d776f/_docs/tasks/rate-limiting.md#understanding-rate-limits

**Comment by geeknoid** [comment]
@mjog, in your doc, the key is not sufficient enough for the backend. If
the same quota descriptor is used by multiple aspects, they will all share
the same set of cells in redis.

**Comment by mandarjog** [comment]
On Wed, May 3, 2017 at 11:14 AM, Martin Taillefer <notifications@github.com>
wrote:

> @mjog, in your doc, the key is not sufficient enough for the backend. If
> the same quota descriptor is used by multiple aspects, they will all share
> the same set of cells in redis.



The key also includes the values of parameters and labels. So if they share
the same redis cell, it is
the user's intent.

**Comment by geeknoid** [comment]
@douglas-reid Yes, that's close to what I'm thinking.

The adapters would use this when interacting with their backends. For example, in the case of the redis adapter, this unique ID would be used to segregate the state produced by one instance of the adapter vs. the other.

**Comment by geeknoid** [comment]
That can't be...

Imagine the CIO declares a QuotaDescriptor for the whole organization.
Individual aspects within the cluster's configuration can use this
descriptor. Different services for example may have locally-defined aspects
that use the same descriptor. These multiple aspects must be independent
from one another, they can't share the same cells.

Imagine if there's a RequestCount descriptor which is defined to have a
single label called "origin.datacenter". If two independent services each
declare an aspect using that descriptor, we want each service to have a
distinct QPS limit for different data center, and not a shared limit
between the two services.

To have a shared limit, they would both need to use the same aspect.

**Comment by douglas-reid** [comment]
@geeknoid I'm sympathetic to the desire to not have tons of adapter definitions floating around for the same backend based on some small detail of config. I think we just need to be careful about introducing an extra layer of (generated) config and what that means for adapter implementations.

Could/should this scope information be passed as Execute() args (`Record([]MetricValue, ScopeKey)`?  Is that more natural? Would that reduce the number of adapter instances throughout the system?

**Comment by geeknoid** [comment]
On the list of breaking changes for post-Alpha is to rejigger what adapters
are, relative to their config. And I think this factors in to the question.

Perhaps a simple model is that an instance of an adapter corresponds to one
"user" of the target backend. So all the data pumped in by one adapter has
the same access permissions and is isolated from the data produced by other
instances of the adapter.

If you have that base assumption, then you get to decide whether you want
this unique id stuff per instance of the adapter, or per request to the
adapter....

**Comment by mandarjog** [comment]
It also necessitates rethinking how aspects are cached. At present, aspects are cached using aspect config. Now we must include the magic aspect_id or aspect_name as part of that key. 

There was great simplicity before in thinking about an aspect being stateless. This meant that 2 identical aspect configs resulted in just 1 actual aspect thru the cache.

**Comment by geeknoid** [comment]
Updated to our new reality, we simply need to give the name of the handler to the adapter when instantiating the handler object. This will give enough context to the adapter to create isolation contexts if it needs to.

**Comment by guptasu** [comment]
So we will be building a new Handler instance from each handler config.. this gives an isolation. Why do they need a name.. debugging ?

**Comment by geeknoid** [comment]
​Oh wait, we don't need this anymore. The adapter config just needs
different credentials/ids explicitly. I'll close the issue.​

**Comment by geeknoid** [comment]
Nope, don't need this given our new adapter model.
