### ISSUE TITLE
Rename attrgen aspect to attrGen

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#672]
We've been using camelCase for aspect names...

**Comment by ZackButcher** [comment]
It should be "attributes"/"attributesManager" (denials/denialsManager, accessLogs/accessLogsManager, etc) if we're following the scheme of the other ones.

**Comment by douglas-reid** [comment]
we want to get away from camel cases, imho.  

> Good package names are short and clear. They are lower case, with no under_scores or mixedCaps.

https://blog.golang.org/package-names

**Comment by kyessenov** [comment]
yeah, it's somewhat controversial but it should be either "attrgen" or "attribute/gen" to be consistent with golang standard library conventions.

**Comment by kyessenov** [comment]
and you guys have way too many managers in the code :)

**Comment by geeknoid** [comment]
Names should be short enough, but not too short...

**Comment by douglas-reid** [comment]
i guess this all depends what you think of the `strconv` package (and similar).

either way, i think this can be addressed post-alpha as part of a larger re-org of the codebase. we want to be sensitive to case handling across OSes, too.

**Comment by geeknoid** [comment]
Doug, is this still relevant?

**Comment by douglas-reid** [comment]
let's punt on this for 0.2.  this is not a p1, imho.

**Comment by geeknoid** [comment]
Obsolete
