### ISSUE TITLE
codecov seems to apply to .md and other files for which it's meaningless

### ISSUE THREAD

**Issue by ldemailly** [istio/mixer#685]
codecov blocks/complain about PRs that only change .md files 

e.g.
https://github.com/istio/mixer/pull/684

**Comment by ldemailly** [comment]
seems like we could add *.md to codecov.yaml but we don't seem to have that file ?
(or I don't see it)

https://docs.codecov.io/docs/ignoring-paths

**Comment by ldemailly** [comment]
looks like it's https://codecov.io/account/gh/istio/yaml
but I'm not an owner so I can't edit it - assigning to one of the istio admins

**Comment by geeknoid** [comment]
Who has rights to this file? I don't...

**Comment by sebastienvas** [comment]
I just changed it.

**Comment by ldemailly** [comment]
Thanks Sebastian ! Martin you are listed in github admins and owners so I thought you would have had access to that file, curious who the admins are then if not https://github.com/orgs/istio/teams/admins nor https://github.com/orgs/istio/people?query=role%3Aowner
