### ISSUE TITLE
Figure out better Grafana access for demo / addon install

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#689]
Right now, we have it getting an external IP and with default creds. This seems... non-ideal.

**Comment by kyessenov** [comment]
Why can't we treat as yet another service and use ingress?

**Comment by douglas-reid** [comment]
No reason.

**Comment by mandarjog** [comment]
We can use ingress but we should also provide instructions on kubectl port forward.

If ingress is not working  (or not installed at all), we don't want other istio services to become inaccessible.

**Comment by douglas-reid** [comment]
in istio/istio#406, load balancer for grafana was removed. at the moment, access will only be available via port-forward or proxy.

**Comment by douglas-reid** [comment]
Closing this for now. Adding to ingress is something we can tackle if there is any demand.
