### ISSUE TITLE
Update servicegraph images / functionality

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#691]
With the change to use `source.labels["app"]` in the metrics `source` expression (from `source.service`), servicegraph no longer shows a single pretty graph (apps are not matched to services).

We should either update the servicegraph example impl to be smarter (with kubernetes code) and/or consider removing it from the docs.

**Comment by douglas-reid** [comment]
cc: @mandarjog per our discussion.

**Comment by ZackButcher** [comment]
To add on, we should consider making the service graph an adapter proper, rather than base it on e.g. prometheus. We have the raw data to construct the graph in a `Metrics` (or upcoming `Trace`) type adapter. The "backend" could be an HTTP server hosted on Mixer.

**Comment by douglas-reid** [comment]
So, I fixed the original issue (this should have been closed).

Shall we move this out to a new issue around making servicegraph a first-class thing?

**Comment by ZackButcher** [comment]
SGTM

**Comment by douglas-reid** [comment]
Closing this.
