### ISSUE TITLE
Strip url from grafana dashboards

### ISSUE THREAD

**Issue by smawson** [istio/mixer#692]
I left my guestbook app running overnight and the internet hammered it with lots of random traffic. Our grafana dashboard tries to show a separate line for each url that was called, which is many many pages of lines each with a single count. So we should collapse those into a single one and allow drilldown if needed, or find some way to limit the number of lines shown or something.

**Comment by douglas-reid** [comment]
To start, I think we want aggregration w/o the "method" dimension included. I'll see if I can get the promql correct and submit PRs and update the published docker image.
