### ISSUE TITLE
Redis Config API Storage backend

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#695]
Redis Store backend should use Redis Keyspace Notifications to subscribe to change stream and implement the full SPI that returns Index. 

It should also return `ChangeNotifier` api and call `NotifyStoreChanged` when a change occurs.

**Comment by jmuk** [comment]
#694 does not support redis sentinel (https://redis.io/topics/sentinel). I will create another PR for that.

**Comment by kyessenov** [comment]
Can we align this with etcd/k8s informers? We shouldn't be hardcoding redis assumptions into mixer.

**Comment by mandarjog** [comment]
@jmuk is this is related to redis HA, then we should treat it separately. Istio is not responsible for redis HA.


@kyessenov The redis adapter *will* have redis specific code. We do not and will not have redis specific code outside the redis adapter.

**Comment by kyessenov** [comment]
How long till we deprecate the current mixer config? Do we need HA redis before then?

**Comment by jmuk** [comment]
I think at least we need to have some steps to set up a redis backend with the initial data.
I've created a tool to port data into a redis server (https://github.com/istio/mixer/pull/759), but I feel like a bit different solution would be needed to deprecate the current mixer configs.

**Comment by geeknoid** [comment]
Tracked by various Galley work items.
