### ISSUE TITLE
Incorrect HTTP code when attempting to POST invalid mixer rule

### ISSUE THREAD

**Issue by esnible** [istio/mixer#707]
When I do ```$ istioctl mixer rule create global myservice.ns.svc.cluster.local --file tests/apps/istioctl/input/mixer-rule-ratings-ratelimit-invalid.yaml
Error: the server responded with the status code 412 but did not return more information```

The error code should be 400, as the data is incorrect.  412 is reserved for requests using rare headers like `If-Unmodified-Since`.

Note that when _istioctl_ is run with `-v 9999` the logs show that the mixer is returning output.  I will open a separate bug for istioctl to report that error.

```
Response Body: {
  "status": {
   "code": 9,
   "message": "2 errors occurred:\n\n* serviceConfig: failed validation\n* /:quotas[0]: failed to parse params: 1 error occurred:\n\n* quotas: aspect validation failed: 1 error occurred:\n\n* maxAmount: must be \u003e= 0"
  }
 }
```

**Comment by douglas-reid** [comment]
Can we mark this issue as closed now?

**Comment by mandarjog** [comment]
yes PR #711 closes this.
