### ISSUE TITLE
Support a list checker that takes additional parameters

### ISSUE THREAD

**Issue by gbrail** [istio/mixer#717]
The "list checker" aspect is powerful and supports a lot of things. For instance, we have been able to easily use it for a very simple "verify API key" use case, in which we configure it to take a parameter from an HTTP header or query parameter and verify that.

However, for more sophisticated verification we need more. For instance, we also want to look at the URL that was passed to the HTTP request. 

In order to do these more complex checks, we'd need either:

1) A "list checker" adapter interface that works like the "ListsAspect" interface, but supports a "CheckList" method that takes more than one parameter. (For instance, we could have one that takes two parameters, one that takes three, and so on. Or we could have one that takes an array of strings. This would work fine for us.)
2) Or, a way to pass all the parameters to the list checker so that a more sophisticated checker can check arbitrary parameters from the request.

**Comment by geeknoid** [comment]
We now have the flexible template model. We're also looking at providing per-adapter augmentation of delivered state.
