### ISSUE TITLE
Review metrics dimensions

### ISSUE THREAD

**Issue by esnible** [istio/mixer#768]
(This is from a Slack discussion on Thursday 5/25)

1. The mixer stores the HTTP Path in a Prometheus label called "method".  The HTTP Method should appear in "method".  The path should appear in a different label (such as "path").
2. The mixer configuration causes FQDNs to be stored in target but hostnames to be stored in source.  It would be best if the default configuration stored source and target similarly.
3. The "source" field for traffic that reaches a microservice via the ingress should have the ingress name as the source.
4. Traffic from the outside into the ingress should also appear in Prometheus.
5. The default configuration records the target pod's version label but not the source pods.  Both the source and target should be recorded by the default configuration.

**Comment by douglas-reid** [comment]
We've had several back-and-forth about the content of each label in the metrics and about what we can properly extract and put in various labels and what should be exposed in general for default metrics.

I'm going to rename this issue to "Review default metrics configuration" to highlight the larger conversation and drive consensus on approach. I will separate out the ingress issues, as I believe that is distinct from content of metrics (mixer is not currently integrated with ingress).

A couple of starting points:

- For input, we get the request headers and source and target UIDs (example: `kubernetes://pod.namespace`).
- Right now, we use the kubernetes adapter to generate the following fields:
   - pod ip
   - pod labels
   - pod name
   - pod namespace
   - fqdn for service (constructed, in part, from a configurable label on the pod)
   - service account name for the pod

We currently construct metrics labels as follows:
```
source: source.labels["app"] | "unknown"
target: target.service | "unknown"
service: target.labels["app"] | "unknown"
method: request.path | "unknown"
version: target.labels["version"] | "unknown"
response_code: response.code | 200
```

At the very least, it seems we could replace `method` and `version` with something like:
```
request_path: request.path | "unknown"
target_version: target.labels["version"] | "unknown"
source_version: source.labels["version"] | "unknown" 
```
It is unclear if it is useful to have a fqdn for target (and/or for source).

**Comment by douglas-reid** [comment]
Moved conversation re: ingress to #649

**Comment by geeknoid** [comment]
Is this issue still relevant? Any new info? Should this be moved to 0.3?

**Comment by douglas-reid** [comment]
It is still relevant, but can be done in separately from everything else. Like a p2.

**Comment by douglas-reid** [comment]
I'm going to close this. Issues 2-5 have been addressed. Issue 1 has been partially addressed (removing method). API Management support will complete Issue 1.
