### ISSUE TITLE
httpFault/abort rules trigger does not send data to Prometheus

### ISSUE THREAD

**Issue by esnible** [istio/mixer#769]
To reproduce, start up bookinfo.

```bash
cat << EOF |
type: route-rule
name: ratings-fail-xpercent
spec:
  destination: ratings.default.svc.cluster.local
  precedence: 2
  httpFault:
    abort:
      percent: 95
      httpStatus: 500
EOF
istioctl replace
```

Drive some traffic.  Then look at the output in Prometheus or ServiceGraph.  The traffic is reduced by the %, but there are no response_code entries for the injected 500s.

**Comment by ZackButcher** [comment]
This is likely a problem in either Envoy's Mixer filter or the mixerclient itself. Mixer just blindly pushes the data we're provided to the metric backend, these missing stats seem to indicate that `Report` calls aren't being made to the mixer by Envoy when it sees a 500.

**Comment by douglas-reid** [comment]
@qiwzhang any ideas what might cause this related to the filter chain?

**Comment by mandarjog** [comment]
Issue moved to [istio/mixerclient #133](https://github.com/istio/mixerclient/issues/133) via [**ZenHub**](https://www.zenhub.com/)
