### ISSUE TITLE
Swap BUILD files to use glob rather than explicitly listing all files in a package

### ISSUE THREAD

**Issue by ZackButcher** [istio/mixer#781]
I forget to include new files in a package's BUILD file all the time - especially test files (which I run in my IDE while writing, no bazel involved). On multiple occasions I've found test files not listed in a BUILD rule in code that's already been checked in.

We should start using globs in the `src` list of our BUILD rules to avoid this; they should look like:

```
go_library(
    name = "go_default_library",
    srcs = glob([
        include = ["*.go"],
        exclude = ["*_test.go"],
    ]),
    visibility = ["<snip>"],
    deps = [
        # deps here
    ],
)

go_test(
    name = "<package name>_test",
    size = "small",
    srcs = glob(["*_test.go"]),
    library = ":go_default_library",
    visibility = ["//visibility:public"],
    deps = [
        # deps here
    ],
)

```

**Comment by ayj** [comment]
Alternatively, you can use [gazelle](https://github.com/bazelbuild/rules_go/tree/master/go/tools/gazelle) to create/maintain your BUILD files, e.g.

```bash
gazelle -go_prefix "istio.io/mixer" -mode fix -repo_root .
```

**Comment by ZackButcher** [comment]
Same root problem though - gazelle lists files explicitly. It's a nice way to bootstrap a new BUILD file, but I find it's not especially useful when I'm updating an existing BUILD file (e.g. typically I know all the deps I need to add because I had to go add them all to the WORKSPACE file anyway, and that's an iterative process since bazel will bail at first missing dep).

**Comment by ayj** [comment]
Maybe I'm misunderstanding the original problem (i.e. "I forget to include new files ...") which gazelle/glaze seem to handle quite well. The following shows that gazell will add missing test targets *and* add new files to existing targets based on package names.

### Before
```bash
$ ls pkg/version/
BUILD  newfile.go  version.go  version_test.go

$ cat pkg/version/BUILD
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "version.go",
    ],
    visibility = ["//visibility:public"],
)
```

### After 

```bash
$ gazelle -go_prefix "istio.io/mixer" pkg/version/

$ cat pkg/version/BUILD
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_prefix", "go_test")

go_library(
    name = "go_default_library",
    srcs = [
        "newfile.go",
        "version.go",
    ],
    visibility = ["//visibility:public"],
)

go_prefix("istio.io/mixer")

go_test(
    name = "go_default_test",
    srcs = ["version_test.go"],
    library = ":go_default_library",
)
```

**Comment by ZackButcher** [comment]
Right, but if we just use globs then we don't need a tool to add files, they're automatically included. Listing files explicitly adds nothing in go - bazel won't allow you to split a go package across multiple build targets so there's no advantage to listing files explicitly in go (unlike e.g. in Java, where you can split a package across targets, useful for removing circular deps etc).

Further, gazelle will insert dependencies for you too - I maintain that that's not very useful right now since much of the time I'm adding dependencies, they're entirely new to the project so I need to add them to the WORKSPACE file first (Gazelle won't add a dependency not already in your WORKSPACE file AFAIK). Maybe once we settle into a state where we're not adding entirely new dependencies as often it'll be more useful, but for now I've found it easier to go add a dep to the WORKSPACE file, then copy+paste it directly into the BUILD target I'm working on.

<hr>

My goal here is to make it harder to make mistakes. If the process is "run this other tool" then that's not accomplishing the goal. Using globs in our build files means it's impossible for a file to be forgotten. After we have globs everywhere we can still use Gazelle to manage/add dependencies in existing BUILD targets.

**Comment by douglas-reid** [comment]
I have a strong dislike for globs -- for reasons perhaps not entirely rational.  What if we use gazelle, but make it part of the pre-commit hooks?

**Comment by ayj** [comment]
For reference, istio.io/manager wraps gazelle in a script to simplify usage (see  https://github.com/istio/manager/blob/master/bin/gazelle)

**Comment by rkpagadala** [comment]
globs are easier to read, + all go files in a given directory have to belong to the same package which is the parent directory name

**Comment by douglas-reid** [comment]
easier to read is in the eye of the beholder ;).  I like being explicit about what we are including in each target. Having a tool do it doesn't seem any different than using the tool to do automated formatting and linting.

Does gazelle expand globs as part of the `fix` mode?  If so, does it make sense to just use it now, instead of having two rewrites of all of our BUILD files ?

**Comment by rkpagadala** [comment]
gazelle expands globs as part of fix mode. I have code for globs, but I am willing to go whichever way the consensus is.

**Comment by kyessenov** [comment]
Last time I tried to switch mixer to gazelle I run into problems with api repo since you have some hacks around WORKSPACE import for api.
