### ISSUE TITLE
Update mixer with new configuration model.

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#798]
Design document for the new template model
[Mixer Template Model Design Doc](
https://docs.google.com/document/d/1GPeeRsooiLAKrdIbIYI5PvuAVPO5jXcNZdHaWZQlZWw/edit#heading=h.o9rrxrqjyry2)

Additional design discussion doc for mixer configuration is described here:
[Mixer Design Decisions](https://docs.google.com/document/d/1elqeOTDCGSaKP7GI0mrNkZDtt0dq8TbarEt0jUNTk-M/edit#)

The samples to configuration to show the above model is in the PR:
https://github.com/guptasu/mixer/pull/13/files

https://github.com/istio/api/pull/128 defines the new model in cnfg proto.

**Comment by guptasu** [comment]
@mandarjog @geeknoid @ZackButcher @douglas-reid

**Comment by guptasu** [comment]
@louiscryan and @smawson

**Comment by guptasu** [comment]
Hi Everyone, now there are examples https://github.com/guptasu/mixer/pull/13/files along with the Design document. These examples are compiled by the Mixer team for clarifying the new Configuration design. Please review them and provide feedback.

**Comment by guptasu** [comment]
@guptasu

**Comment by guptasu** [comment]
@wora

**Comment by geeknoid** [comment]
Here's the document where this model is discussed:

https://docs.google.com/document/d/1elqeOTDCGSaKP7GI0mrNkZDtt0dq8TbarEt0jUNTk-M/edit#heading=h.72u35jgig7u

**Comment by guptasu** [comment]
https://github.com/istio/mixer/issues/803

**Comment by guptasu** [comment]
#803

**Comment by guptasu** [comment]
#803

**Comment by guptasu** [comment]
https://github.com/istio/api/pull/128

**Comment by geeknoid** [comment]
Can we close this?

**Comment by guptasu** [comment]
this is covered in the epic 'adapter model' story + other bugs.

**Comment by guptasu** [comment]
@geeknoid done
