### ISSUE TITLE
PUT (and DELETE) operations should be protected

### ISSUE THREAD

**Issue by ldemailly** [istio/mixer#800]
right now if you can reach the mixer port you can push changes without any security/authentication/authorization checks, e.g.
```
curl -v  http://localhost:9094/api/v1/scopes/global/subjects/foo.svc.cluster.local/rules --data-binary @quota.yaml -X PUT -H "Content-Type: application/yaml"
```
just works, we can't rely solely on network level access control

ps: merge if this is a duplicate, a search didn't find this issue already opened

**Comment by ayj** [comment]
This problem is more general than the mixer config and PUT/DELETE. The Istio API/Configuration server doesn't have any support for auth at the moment. I opened https://github.com/istio/pilot/issues/840 to track this issue.
