### ISSUE TITLE
Cognitive overhead of 'type' in new configuration model

### ISSUE THREAD

**Issue by louiscryan** [istio/mixer#802]
@mandarjog @geeknoid @smawson @douglas-reid 

The new configuration model as outlined in

https://github.com/istio/mixer/issues/798

Introduces an explicit 'type' declaration separate from the 'constructor' pattern for the creation of 'template instances' to pass to the Mixer.

This increase the amount of configuration complexity and leads to a lack of readability. Specifically

- Constructors and Types will almost universally be 1:1 therefore the indirection is unnecessary. In particular given that a Constructor provides the same amount of structural and typing information via inference.

- The separation requires both things to be named. The examples in the linked issue used 'semantic' names for types when they should be logically semantic-free. The examples then had to create unnatural names for the constructors. This creates an overall legibility issue for little to no value.

As discussed with Martin this issue should be resolved before Beta but can be deferred until after the underlying execution model is working as it is a syntactic issue albeit an important one.

**Comment by geeknoid** [comment]
Types have been removed from the config format.
