### ISSUE TITLE
Plumb adapter.Env to more places

### ISSUE THREAD

**Issue by ZackButcher** [istio/mixer#820]
Today we only provide the Environment ([`adapter.Env`](https://github.com/istio/mixer/blob/master/pkg/adapter/adapter.go#L66-L95), [implemented here](https://github.com/istio/mixer/blob/master/pkg/adapterManager/env.go)) in the `New*Aspect` methods, with the idea that if the adapter needs to use the environment later (e.g. at runtime for logging) it'll store a reference.

I'd like for us to change this pattern to instead provide the Env per request, as an argument to each Aspect's runtime method (i.e. change the Metric aspect's `Record([]adapter.Value) error` to `Record([]adapter.Value, adapter.Env) error`). This would let us provide per-request metadata via the Env, and enable behavior like having Env.Log write to the trace span for this request instead of just logging locally.

One tradeoff to this proposal is that anything happening out of band of the request loses the ability to hold on to the environment to use later, which could be painful. As an example, in the Stackdriver adapter we implement batching. We then send batches of data to Stackdriver based on a ticker. The method called each tick is out of bad of a request, so it can't get its hands on an `Env` to use to log failures. There are solutions to this, however (e.g. change `Env.ScheduleWork`/`Env.ScheduleDaemon` to provide a copy of the current Env to their callback function).

**Comment by guptasu** [comment]
@geeknoid  Help on this issue pls. Before we port adapters, it is nice to resolve this so the public interface will not change. I can look into it next week, however, I would prefer to work on E2E test from Monday for the new config model before we have a Green light for adapter porting.

**Comment by geeknoid** [comment]
I'll spend some time on this today.

**Comment by geeknoid** [comment]
Env comes in at build time, that's what we want. So Closing.
