### ISSUE TITLE
Redis driver test will fail in certain developer environments

### ISSUE THREAD

**Issue by cmluciano** [istio/mixer#830]
This [driver_test.go](https://github.com/istio/mixer/blob/master/adapter/redisquota/driver_test.go#L55-L64) makes assumptions about the developer environment that it is run in. If a developer has redis started in the background (as was the case with my home-brew setup), the test will fail because it believes that the redis instance should not exist.

I can submit a PR to do one of the following:
- clarify why the test might be failing
- remove the test since it is testing the developer environment rather than the adapter itself

**Comment by geeknoid** [comment]
Tracked by Galley work items.
