### ISSUE TITLE
Create an adapter testing framework.

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#834]
We need to make it easy for adapter authors to ensure their adapters follow the requirements for the templates they implement. Further, template authors need to be able to easily extend the framework to enable others to implement against their template.

**Comment by guptasu** [comment]
@geeknoid @manlinl is working on this, right ?

**Comment by geeknoid** [comment]
Yes, but until he accepts the invitation I sent from GitHub for him to join
the team, I can't assign the issue to him.
