### ISSUE TITLE
Enable adapters to be hosted in 'foreign' repos

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#836]
Right now, adapter source code must be located within the mixer repo. We want to make it possible for an instance of Mixer to be built out of adapters coming from any repo.

**Comment by ZackButcher** [comment]
FWIW we could even go so far as to move our own adapters into their own istio/mixer-adapters repo. Then "foreign" adapters aren't a special case, they're the only case.

**Comment by geeknoid** [comment]
In fact, doing so might simplify things. The only way to build Mixer would be with a constellation of adapter repos, no special casing for locally hosted adapters.

**Comment by douglas-reid** [comment]
Technically, we could attempt this without any further changes. This should an area where bazel would shine.

Of course, the question, as I see it, is: how much build system wrangling is acceptable to consider this issue closed? Is it OK to require updating/editing of the WORKSPACE?  What about other BUILD files throughout? What about edits to things like `inventory.go`?

It seems like we should strive to limit the number of modifications -- maybe have some script that will do the manipulations for you based on repo & sha, if possible ?

**Comment by geeknoid** [comment]
Here's my 'dream' scenario.

User has a repo which holds some custom adapter. They're also using some adapters coming from a distant repo, and of have a clone or fork of the Mixer repo. Of course, these various repos can contain template definitions, adapter code, and adapter tests.

To create a Mixer instance, the user clones the new istio/mixer repo. In their clone of the repo, they change the new ADAPTERS file at the root of the repo to only mention the adapters they want to use. The ADAPTERS file specifies the set of repos+SHA+paths for each adapter and/or template to pull into the Mixer binary.

User does 'bazel build' in this repo and they get a Mixer binary. We auto-generate inventory files and any other goo.

**Comment by douglas-reid** [comment]
@geeknoid I think we can get close to that today -- (we'd need a temporary `updateAdapters.sh` script that did the code munging for us for a little while). Instead of an ADAPTERS file, we might have something like an `deps.bzl` file (a la: https://github.com/pubref/rules_protobuf/blob/master/gogo/deps.bzl).

**Comment by douglas-reid** [comment]
Initial work in https://github.com/istio/mixer/pull/1108.

**Comment by douglas-reid** [comment]
This is now possible. I've verified with an adapter built in `git@github.com:douglas-reid/mixer-noop-reporter.git`.

It might not be pretty, but it is possible.

**Comment by douglas-reid** [comment]
I'm going to close this issue, as I think the minimum bar has been met.
