### ISSUE TITLE
Shuffle directory structure

### ISSUE THREAD

**Issue by geeknoid** [istio/mixer#86]
Current proposal:

istio.io/mixer/cmd/mixer/main.go
istio.io/mixer/pkg/adapter/...
istio.io/mixer/pkg/api/... (most of what's currently in mixer/server/*.go)
istio.io/mixer/​pkg/config/...
istio.io/mixer/pkg/attribute/...
istio.io/mixer/doc/...
istio.io/mixer/example/...

**Comment by geeknoid** [comment]
Slight update:

istio.io/mixer/cmd/mixer/main.go
istio.io/mixer/cmd/mixerclient/main.go
istio.io/mixer/pkg/adapter/... (adapter support
istio.io/mixer/pkg/api/... (most of what's currently in mixer/server/*.go)
istio.io/mixer/​pkg/config/...
istio.io/mixer/pkg/attribute/...
istio.io/mixer/doc/...
istio.io/mixer/adapter/... (individual adapters)
istio.io/mixer/example/...

This structure provides high-level functional separation. We can have multiple commands for various utilities, we have room for examples & docs, and we have a flat set of adapters and flat set of support packages. This generally matches how k8s is organized.

Any counter proposals?

@mandarjog @douglas-reid

**Comment by mandarjog** [comment]
yup, let's go for it.
pkg should have importable reusable packages. 
LGTM.

**Comment by geeknoid** [comment]
OK, as soon as my current PR is in, I'll move this stuff around.

**Comment by douglas-reid** [comment]
one nit. 

why not:

mixer/cmd/server
mixer/cmd/client

?

**Comment by geeknoid** [comment]
Yeah /server and /client looks good.

On a related note, what should we call our binaries? "server" and "client" seems a tad generic and unhelpful to the casual observer. Maybe mixserver and mixclient?

**Comment by douglas-reid** [comment]
mixserver sgtm.  is it worth using something shorter than client for the client?  maybe mixcli or mixctl or or mixcmd or even mixc ?

**Comment by geeknoid** [comment]
How about then:

istio.io/mixer/cmd/mixs
istio.io/mixer/cmd/mixc

with mixs and mixc as our binaries?

**Comment by douglas-reid** [comment]
What if we leave the dirs as server and client but have the go_binary rules named something like "mixs" and "mixc" or whatever?  (the go build equivalent of the -o option)

**Comment by geeknoid** [comment]
OK
