### ISSUE TITLE
Add Prometheus integration

### ISSUE THREAD

**Issue by douglas-reid** [istio/mixer#89]
This should exercise the config -> aspect -> adapter story from start to finish. When complete, we should ask the prometheus team to take a look and provide feedback on the approach and implementation.

**Comment by douglas-reid** [comment]
I think we can close this now (@ZackButcher to verify). We have an initial impl. Refinements sure to follow, but they can be tracked in other issues.

**Comment by ZackButcher** [comment]
Yeah, no reason to keep this around: we have all the code in, verified it works e2e.
