### ISSUE TITLE
Port all adapters for metric aspect to the template model

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#918]

**Comment by sakshigoel12** [comment]
Please update assignee!

**Comment by geeknoid** [comment]
Can we close this?

**Comment by ZackButcher** [comment]
Statsd and Prometheus are done, Stackdriver is in process, and @redhotpenguin will be moving the Circonus adapter over.

**Comment by ZackButcher** [comment]
Actually, my mistake, Stackdriver was already merged. Closing this as the Circonus adapter is not yet checked in.
