### ISSUE TITLE
Encrypt Proxy <-> Mixer traffic

### ISSUE THREAD

**Issue by spikecurtis** [istio/mixer#924]
We need to (perhaps optionally) enable TLS on the connection Proxy makes to Mixer for Check() and Report() as they may contain sensitive data.

I see two reasonable options:

1. Add a Proxy sidecar to the Mixer service.
2. Directly add TLS support to Mixer.

I think (1.) is more desirable for architectural consistency.  What do people think?

**Comment by ZackButcher** [comment]
In the long run we plan to run Istio on Istio, i.e. control plane components will run behind a sidecar mesh proxy. However, there are a few wrinkles we need to iron out for the Envoy in front of Mixer specifically.

gRPC supports TLS out of the box. In the short term it seems most reasonable to enable gRPC TLS between proxies and Mixer, knowing that in the long run it'll be handled by the sidecar in front of Mixer.

**Comment by spikecurtis** [comment]
If we used gRPC's TLS support we need to solve the problem of keys and certs.  We should be able to use Istio Auth to get them as a k8s secret, right?

**Comment by ZackButcher** [comment]
Yes, that's my understanding: we should be able to use the Istio CA's certs, retrieving them in Mixer as k8s secrets. I don't believe anyone has taken time to think about the specific implementation details and what'll be required to make it work, though.

**Comment by lizan** [comment]
@rkpagadala is working on securing Istio components, which includes securing transport between proxy, mixer, pilot, galley etc.

**Comment by geeknoid** [comment]
Are there other issues tracking the general work is slapping a proxy in front of all Istio components? If so, can we close this particular issue?

**Comment by geeknoid** [comment]
Is this really a P0 for 0.2? We won't ship 0.2 unless this is done?

**Comment by rkpagadala** [comment]
That is the plan

**Comment by costinm** [comment]
I think the real blocker is sidecar -> pilot, since certs and configs that
may bypass cert are sent.

As long as mixer is not used to enforce auth policies - IMHO it is slightly
lower priority, but I'm not
clear how much damage can be done by a malicious mixer. I suspect a bit
less than a malicious
pilot.

**Comment by spikecurtis** [comment]
Auth policy in Mixer is pretty nascent for 0.2, but still present and usable.

**Comment by geeknoid** [comment]
This doesn't sound like a P0 to me. We wouldn't block the 0.2 release if
this feature is not complete.

**Comment by rkpagadala** [comment]
After discussion, changing to P1

**Comment by costinm** [comment]
Thanks - IMHO we can make it a P0 for 0.3 or 0.4 ( wherever we land 'not on
the same VPC/VPN' ).
The work on adding a  sidecar for pilot should be applicable for sidecar to
mixer - as well
as mixer to other backends.

**Comment by geeknoid** [comment]
Covered by #1470
