### ISSUE TITLE
Implement bazel rule to create mixer build with supported templates.

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#948]
We need a build rule that pulls in all the templates a mixer wants to support, does codegen of required helper files and then compiles the mixer with the generated files. The built mixer now supports the templates that user had expressed in the build rule.

Additionally, in the same build rule, we need to also take adapters that a mixer will be built with. From that list we will code generate an inventory file something like this : https://github.com/istio/mixer/blob/master/adapter/inventory2.gen.go

Upon chatting with @geeknoid  and @douglas-reid one way the build target would look is

mixer_gen(
  pkgs = ["/adapters", "/pkg/adapterManager", ...]
  templates = ["/template/metric:<NameOfTargetMixerProtoLibrary>", ...]
  adapters = ["/adapter/memQuota", ...]
)

Chatted with @douglas-reid and he will be working on this.

**Comment by douglas-reid** [comment]
@guptasu you mentioned that this was doable now earlier today. can you expand on any updates here?

**Comment by douglas-reid** [comment]
Marking as resolved.
