### ISSUE TITLE
Investigate how can we undo "output_to_workspace": True

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#949]
PR https://github.com/istio/mixer/pull/935/files#diff-c8bd90f421d92c7dfb72908cbd50081cR110 added `"output_to_workspace": True`, to wireup the generated augmented template proto file.

This line gives warning :
* - Generating files into the workspace...  This is potentially           *
*   dangerous (may overwrite existing files) and violates bazel's         *
*   sandbox policy.     

Seems like it is not a recommended thing to do. To unblock the PR , we submitted this with the warning. We need to now investigate and see what is going on. 

Assigning to @douglas-reid for help to understand on what might be going on. 

@douglas-reid, please assign it back to me if you don't have cycles to investigate or if you have some pointers on potential cause and want me to finish the fix.

**Comment by douglas-reid** [comment]
Filed: https://github.com/pubref/rules_protobuf/issues/116. No updates currently. Will try reaching out to bazel team.

**Comment by douglas-reid** [comment]
Have sent PR to fix root cause: https://github.com/pubref/rules_protobuf/pull/118.

Also, have put in interim warning suppression PR: https://github.com/istio/mixer/pull/1180.
