### ISSUE TITLE
glog: fix or  find a replacement

### ISSUE THREAD

**Issue by mandarjog** [istio/mixer#95]
glog.init() method registers standard golang flags.

k8sclient go client vendors a version of glog. This makes it hard to use glog inside istio with k8sclient. 

https://github.com/kubernetes/kubernetes/issues/35096

options
1. fork and fix glog, so it does not auto register
2. Find a way to build it in bazel by removing dependency.

**Comment by kyessenov** [comment]
3. Use another logging library.

**Comment by douglas-reid** [comment]
If we decide to go another way for logging, we will need to update our logging documentation in the devel doc.

**Comment by kyessenov** [comment]
Maybe you should another adapter for glog so I can call it from Manager? :)

**Comment by geeknoid** [comment]
This doesn't seem to be a problem when bazel builds, so closing for now.
