### ISSUE TITLE
Use k8s CRD as the config store

### ISSUE THREAD

**Issue by jmuk** [istio/mixer#983]
This is a task related to our recent decision on Galley; first we will use kubernetes custom resource definitions (CRDs) to store configs for istio. However, this new config data model is different from what mixer currently has, and it is not obvious how we make this transition.

I think we should take the following steps:

step 1: implement k8s client as a "store" implementation
----

The initial attempt would be to build the k8s client as an implementation of `pkg/config/store` (especially a `Watcher`). This will be inefficient because it needs to reformat the k8s data into the serialized yaml data and then re-validate them. No external webhooks.

step 2: introduce the validation webhook / reformat apiserver
----

Currently `pkg/config/apiserver.go` receives the requests from `istioctl`, validates the config data, and stores it to the server.

We want to replace the validation by the external admission webhook. During the transition, first webhooks are introduced. Also apiserver.go will be reformed to store the config data directly into CRD and let webhooks do the rest.

step 3: refactor validation / storage abstraction
----

Related to https://github.com/istio/mixer/issues/910. k8s client can emit updates per "kind" (i.e. type of configs), it is better to refactor the validator and storage abstraction to fit with the new config data model.

step 4: the retirement of the old config data
----

Updates on e2e test scenario, installation scripts for the predefined data (to `istio/istio`), and removal of the old code.

----

This issue is for tracking tasks for myself. Here's the notes:
- [ ] step1: k8s client as a store implementation
- step2
   - [ ] a: validation webhooks
   - [ ] b: reformat apiservers
- [ ] step3: refactoring of validator and storage
- step4
   - [ ] a: e2e update
   - [ ] b: installation data and scripts
   - [ ] c: removal of old code

**Comment by geeknoid** [comment]
Can we close this?

**Comment by jmuk** [comment]
yes.
