### ISSUE TITLE
Implement templates for all mixer's provided built-in templates.

### ISSUE THREAD

**Issue by guptasu** [istio/mixer#997]
Mixer will have built in templates that adapter authors can use. This issue is to ensure we create a  consistent looking templates protos under /template directory.

The new templates are similar to https://github.com/mixer/tree/master/template/sample/(check/quota/report), 
- we just need to create proto file and a BUILD file.
- Add the name of the templates inside the script https://github.com/istio/mixer/blob/master/pkg/template/generateTemplateGenGo.sh to have new template related code wireup inside the mixer core framework. NOTE: also update the /pkg/template/BUILD file for all the template dirs you have added inside the script

**Comment by guptasu** [comment]
@geeknoid  and I chatted and we need to support  
- enums and sub messags inside a template
- support gogo attribues to do fancy stuff like use go timestamp in case of protobuf.DateTime inside the generated go code.

**Comment by geeknoid** [comment]
All templates are in for 0.2
